// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/integer_typespec.h>
#include <uhdm/expr.h>

void bind_IntegerTypespec(py::module_& m) {
  py::class_<uhdm::IntegerTypespec, uhdm::Typespec, std::unique_ptr<uhdm::IntegerTypespec, py::nodelete>> cls(m, "IntegerTypespec");
  cls.def_property_readonly("expr", [](uhdm::IntegerTypespec* self) { return self->getExpr(); }, py::return_value_policy::reference);
  cls.def_property_readonly("signed", &uhdm::IntegerTypespec::getSigned);
}
