// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/let_decl.h>

void bind_LetDecl(py::module_& m) {
  py::class_<uhdm::LetDecl, std::unique_ptr<uhdm::LetDecl, py::nodelete>> cls(m, "LetDecl");
  cls.def_property_readonly("name", &uhdm::LetDecl::getName);
}
