// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/enum_const.h>

void bind_EnumConst(py::module_& m) {
  py::class_<uhdm::EnumConst, std::unique_ptr<uhdm::EnumConst, py::nodelete>> cls(m, "EnumConst");
  cls.def_property_readonly("name", &uhdm::EnumConst::getName);
  cls.def_property_readonly("decompile", &uhdm::EnumConst::getDecompile);
}
