// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/gen_scope.h>
#include <uhdm/alias_stmt.h>
#include <uhdm/clocking_block.h>
#include <uhdm/cont_assign.h>
#include <uhdm/def_param.h>
#include <uhdm/expr.h>
#include <uhdm/gen_scope_array.h>
#include <uhdm/interface.h>
#include <uhdm/interface_array.h>
#include <uhdm/module.h>
#include <uhdm/module_array.h>
#include <uhdm/net.h>
#include <uhdm/primitive.h>
#include <uhdm/primitive_array.h>
#include <uhdm/process_stmt.h>
#include <uhdm/program.h>
#include <uhdm/task_func.h>
#include <uhdm/tf_call.h>

void bind_GenScope(py::module_& m) {
  py::class_<uhdm::GenScope, uhdm::Scope, std::unique_ptr<uhdm::GenScope, py::nodelete>> cls(m, "GenScope");
  cls.def_property_readonly("index", [](uhdm::GenScope* self) { return self->getIndex(); }, py::return_value_policy::reference);
  cls.def_property_readonly("array_member", &uhdm::GenScope::getArrayMember);
  cls.def_property_readonly("protected", &uhdm::GenScope::getProtected);
  cls.def_property_readonly("implicit_decl", &uhdm::GenScope::getImplicitDecl);
  cls.def_property_readonly("net", [](uhdm::GenScope* self) {
    std::vector<uhdm::Net*> res;
    if (auto* vec = self->getNets()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("process", [](uhdm::GenScope* self) {
    std::vector<uhdm::Process*> res;
    if (auto* vec = self->getProcess()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("cont_assign", [](uhdm::GenScope* self) {
    std::vector<uhdm::ContAssign*> res;
    if (auto* vec = self->getContAssigns()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("module", [](uhdm::GenScope* self) {
    std::vector<uhdm::Module*> res;
    if (auto* vec = self->getModules()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("module_array", [](uhdm::GenScope* self) {
    std::vector<uhdm::ModuleArray*> res;
    if (auto* vec = self->getModuleArrays()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("primitive", [](uhdm::GenScope* self) {
    std::vector<uhdm::Primitive*> res;
    if (auto* vec = self->getPrimitives()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("primitive_array", [](uhdm::GenScope* self) {
    std::vector<uhdm::PrimitiveArray*> res;
    if (auto* vec = self->getPrimitiveArrays()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("def_param", [](uhdm::GenScope* self) {
    std::vector<uhdm::DefParam*> res;
    if (auto* vec = self->getDefParams()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("gen_scope_array", [](uhdm::GenScope* self) {
    std::vector<uhdm::GenScopeArray*> res;
    if (auto* vec = self->getGenScopeArrays()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("program", [](uhdm::GenScope* self) {
    std::vector<uhdm::Program*> res;
    if (auto* vec = self->getPrograms()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("program_array", [](uhdm::GenScope* self) {
    std::vector<uhdm::Program*> res;
    if (auto* vec = self->getProgramArrays()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("interface", [](uhdm::GenScope* self) {
    std::vector<uhdm::Interface*> res;
    if (auto* vec = self->getInterfaces()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("interface_array", [](uhdm::GenScope* self) {
    std::vector<uhdm::InterfaceArray*> res;
    if (auto* vec = self->getInterfaceArrays()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("aliases", [](uhdm::GenScope* self) {
    std::vector<uhdm::Alias*> res;
    if (auto* vec = self->getAliases()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("clocking_block", [](uhdm::GenScope* self) {
    std::vector<uhdm::ClockingBlock*> res;
    if (auto* vec = self->getClockingBlocks()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("task_func", [](uhdm::GenScope* self) {
    std::vector<uhdm::TaskFunc*> res;
    if (auto* vec = self->getTaskFuncs()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("sys_task_call", [](uhdm::GenScope* self) {
    std::vector<uhdm::TFCall*> res;
    if (auto* vec = self->getSysTaskCalls()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
}
