// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/multiclock_sequence_expr.h>

void bind_MulticlockSequenceExpr(py::module_& m) {
  py::class_<uhdm::MulticlockSequenceExpr, std::unique_ptr<uhdm::MulticlockSequenceExpr, py::nodelete>> cls(m, "MulticlockSequenceExpr");
}
