// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/gen_for.h>

void bind_GenFor(py::module_& m) {
  py::class_<uhdm::GenFor, uhdm::GenScope, std::unique_ptr<uhdm::GenFor, py::nodelete>> cls(m, "GenFor");
}
