// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/begin.h>

void bind_Begin(py::module_& m) {
  py::class_<uhdm::Begin, uhdm::Scope, std::unique_ptr<uhdm::Begin, py::nodelete>> cls(m, "Begin");
  cls.def_property_readonly("end_label", &uhdm::Begin::getEndLabel);
}
