// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/interface_array.h>

void bind_InterfaceArray(py::module_& m) {
  py::class_<uhdm::InterfaceArray, uhdm::InstanceArray, std::unique_ptr<uhdm::InterfaceArray, py::nodelete>> cls(m, "InterfaceArray");
}
