// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/fork_stmt.h>

void bind_ForkStmt(py::module_& m) {
  py::class_<uhdm::ForkStmt, uhdm::Scope, std::unique_ptr<uhdm::ForkStmt, py::nodelete>> cls(m, "ForkStmt");
  cls.def_property_readonly("end_label", &uhdm::ForkStmt::getEndLabel);
}
