// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/ordered_wait.h>

void bind_OrderedWait(py::module_& m) {
  py::class_<uhdm::OrderedWait, uhdm::Waits, std::unique_ptr<uhdm::OrderedWait, py::nodelete>> cls(m, "OrderedWait");
}
