// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/gen_stmt.h>

void bind_GenStmt(py::module_& m) {
  py::class_<uhdm::GenStmt, std::unique_ptr<uhdm::GenStmt, py::nodelete>> cls(m, "GenStmt");
  cls.def_property_readonly("label", &uhdm::GenStmt::getLabel);
}
