// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/disable.h>

void bind_Disable(py::module_& m) {
  py::class_<uhdm::Disable, uhdm::Disables, std::unique_ptr<uhdm::Disable, py::nodelete>> cls(m, "Disable");
}
