// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/gen_scope_array.h>
#include <uhdm/gen_scope.h>
#include <uhdm/variable.h>

void bind_GenScopeArray(py::module_& m) {
  py::class_<uhdm::GenScopeArray, std::unique_ptr<uhdm::GenScopeArray, py::nodelete>> cls(m, "GenScopeArray");
  cls.def_property_readonly("name", &uhdm::GenScopeArray::getName);
  cls.def_property_readonly("full_name", &uhdm::GenScopeArray::getFullName);
  cls.def_property_readonly("gen_var", [](uhdm::GenScopeArray* self) { return self->getGenVar(); }, py::return_value_policy::reference);
  cls.def_property_readonly("gen_scope", [](uhdm::GenScopeArray* self) {
    std::vector<uhdm::GenScope*> res;
    if (auto* vec = self->getGenScopes()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
}
