// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/preproc_macro_instance.h>

void bind_PreprocMacroInstance(py::module_& m) {
  py::class_<uhdm::PreprocMacroInstance, std::unique_ptr<uhdm::PreprocMacroInstance, py::nodelete>> cls(m, "PreprocMacroInstance");
  cls.def_property_readonly("name", &uhdm::PreprocMacroInstance::getName);
}
