// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/if_stmt.h>

void bind_IfStmt(py::module_& m) {
  py::class_<uhdm::IfStmt, uhdm::AtomicStmt, std::unique_ptr<uhdm::IfStmt, py::nodelete>> cls(m, "IfStmt");
}
