// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/delay_term.h>

void bind_DelayTerm(py::module_& m) {
  py::class_<uhdm::DelayTerm, std::unique_ptr<uhdm::DelayTerm, py::nodelete>> cls(m, "DelayTerm");
}
