// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/program_array.h>

void bind_ProgramArray(py::module_& m) {
  py::class_<uhdm::ProgramArray, uhdm::InstanceArray, std::unique_ptr<uhdm::ProgramArray, py::nodelete>> cls(m, "ProgramArray");
}
