// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/method_task_call.h>
#include <uhdm/expr.h>

void bind_MethodTaskCall(py::module_& m) {
  py::class_<uhdm::MethodTaskCall, uhdm::TFCall, std::unique_ptr<uhdm::MethodTaskCall, py::nodelete>> cls(m, "MethodTaskCall");
  cls.def_property_readonly("user_defn", &uhdm::MethodTaskCall::getUserDefn);
  cls.def_property_readonly("prefix", [](uhdm::MethodTaskCall* self) { return self->getPrefix(); }, py::return_value_policy::reference);
}
