// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/constr_if_else.h>

void bind_ConstrIfElse(py::module_& m) {
  py::class_<uhdm::ConstrIfElse, uhdm::ConstraintExpr, std::unique_ptr<uhdm::ConstrIfElse, py::nodelete>> cls(m, "ConstrIfElse");
}
