// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/extends.h>
#include <uhdm/expr.h>
#include <uhdm/ref_typespec.h>

void bind_Extends(py::module_& m) {
  py::class_<uhdm::Extends, std::unique_ptr<uhdm::Extends, py::nodelete>> cls(m, "Extends");
  cls.def_property_readonly("class_typespec", [](uhdm::Extends* self) { return self->getClassTypespec(); }, py::return_value_policy::reference);
  cls.def_property_readonly("argument", [](uhdm::Extends* self) {
    std::vector<uhdm::Expr*> res;
    if (auto* vec = self->getArguments()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
}
