// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/gen_scope.h>

void bind_GenScope(py::module_& m) {
  py::class_<uhdm::GenScope, uhdm::Scope, std::unique_ptr<uhdm::GenScope, py::nodelete>> cls(m, "GenScope");
  cls.def_property_readonly("array_member", &uhdm::GenScope::getArrayMember);
  cls.def_property_readonly("protected", &uhdm::GenScope::getProtected);
  cls.def_property_readonly("implicit_decl", &uhdm::GenScope::getImplicitDecl);
}
