// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/checker_inst_port.h>

void bind_CheckerInstPort(py::module_& m) {
  py::class_<uhdm::CheckerInstPort, std::unique_ptr<uhdm::CheckerInstPort, py::nodelete>> cls(m, "CheckerInstPort");
}
