// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/alias_stmt.h>

void bind_Alias(py::module_& m) {
  py::class_<uhdm::Alias, std::unique_ptr<uhdm::Alias, py::nodelete>> cls(m, "Alias");
}
