// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/function.h>

void bind_Function(py::module_& m) {
  py::class_<uhdm::Function, uhdm::TaskFunc, std::unique_ptr<uhdm::Function, py::nodelete>> cls(m, "Function");
}
