// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/disables.h>

void bind_Disables(py::module_& m) {
  py::class_<uhdm::Disables, uhdm::AtomicStmt, std::unique_ptr<uhdm::Disables, py::nodelete>> cls(m, "Disables");
}
