// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/dist_item.h>

void bind_DistItem(py::module_& m) {
  py::class_<uhdm::DistItem, std::unique_ptr<uhdm::DistItem, py::nodelete>> cls(m, "DistItem");
}
