// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/process_stmt.h>
#include <uhdm/attribute.h>
#include <uhdm/module.h>

void bind_Process(py::module_& m) {
  py::class_<uhdm::Process, std::unique_ptr<uhdm::Process, py::nodelete>> cls(m, "Process");
  cls.def_property_readonly("module", [](uhdm::Process* self) { return self->getModule(); }, py::return_value_policy::reference);
  cls.def_property_readonly("attribute", [](uhdm::Process* self) {
    std::vector<uhdm::Attribute*> res;
    if (auto* vec = self->getAttributes()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
}
