// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/named_event_array.h>

void bind_NamedEventArray(py::module_& m) {
  py::class_<uhdm::NamedEventArray, std::unique_ptr<uhdm::NamedEventArray, py::nodelete>> cls(m, "NamedEventArray");
}
