// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/task_func_decl.h>

void bind_TaskFuncDecl(py::module_& m) {
  py::class_<uhdm::TaskFuncDecl, std::unique_ptr<uhdm::TaskFuncDecl, py::nodelete>> cls(m, "TaskFuncDecl");
  cls.def_property_readonly("full_name", &uhdm::TaskFuncDecl::getFullName);
  cls.def_property_readonly("method", &uhdm::TaskFuncDecl::getMethod);
  cls.def_property_readonly("virtual", &uhdm::TaskFuncDecl::getVirtual);
  cls.def_property_readonly("automatic", &uhdm::TaskFuncDecl::getAutomatic);
  cls.def_property_readonly("dpi_pure", &uhdm::TaskFuncDecl::getDPIPure);
  cls.def_property_readonly("dpi_context", &uhdm::TaskFuncDecl::getDPIContext);
  cls.def_property_readonly("dpi_c_identifier", &uhdm::TaskFuncDecl::getDPICIdentifier);
}
