// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/string_typespec.h>

void bind_StringTypespec(py::module_& m) {
  py::class_<uhdm::StringTypespec, uhdm::Typespec, std::unique_ptr<uhdm::StringTypespec, py::nodelete>> cls(m, "StringTypespec");
}
