// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/module.h>

void bind_Module(py::module_& m) {
  py::class_<uhdm::Module, uhdm::Instance, std::unique_ptr<uhdm::Module, py::nodelete>> cls(m, "Module");
  cls.def_property_readonly("top_module", &uhdm::Module::getTopModule);
  cls.def_property_readonly("end_label", &uhdm::Module::getEndLabel);
}
