// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/immediate_assert.h>

void bind_ImmediateAssert(py::module_& m) {
  py::class_<uhdm::ImmediateAssert, uhdm::AtomicStmt, std::unique_ptr<uhdm::ImmediateAssert, py::nodelete>> cls(m, "ImmediateAssert");
}
