// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/tchk_term.h>

void bind_TchkTerm(py::module_& m) {
  py::class_<uhdm::TchkTerm, std::unique_ptr<uhdm::TchkTerm, py::nodelete>> cls(m, "TchkTerm");
}
