// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/class_defn.h>
#include <uhdm/class_defn.h>
#include <uhdm/class_typespec.h>
#include <uhdm/constraint.h>
#include <uhdm/extends.h>
#include <uhdm/task_func.h>
#include <uhdm/task_func_decl.h>

void bind_ClassDefn(py::module_& m) {
  py::class_<uhdm::ClassDefn, uhdm::Scope, std::unique_ptr<uhdm::ClassDefn, py::nodelete>> cls(m, "ClassDefn");
  cls.def_property_readonly("virtual", &uhdm::ClassDefn::getVirtual);
  cls.def_property_readonly("automatic", &uhdm::ClassDefn::getAutomatic);
  cls.def_property_readonly("extends", [](uhdm::ClassDefn* self) { return self->getExtends(); }, py::return_value_policy::reference);
  cls.def_property_readonly("method", [](uhdm::ClassDefn* self) {
    std::vector<uhdm::TaskFunc*> res;
    if (auto* vec = self->getMethods()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("task_func_decl", [](uhdm::ClassDefn* self) {
    std::vector<uhdm::TaskFuncDecl*> res;
    if (auto* vec = self->getTaskFuncDecls()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("constraint", [](uhdm::ClassDefn* self) {
    std::vector<uhdm::Constraint*> res;
    if (auto* vec = self->getConstraints()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("derived_classes", [](uhdm::ClassDefn* self) {
    std::vector<uhdm::ClassDefn*> res;
    if (auto* vec = self->getDerivedClasses()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("class_typespec", [](uhdm::ClassDefn* self) {
    std::vector<uhdm::ClassTypespec*> res;
    if (auto* vec = self->getClassTypespecs()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("end_label", &uhdm::ClassDefn::getEndLabel);
}
