// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/interface_tf_decl.h>

void bind_InterfaceTFDecl(py::module_& m) {
  py::class_<uhdm::InterfaceTFDecl, std::unique_ptr<uhdm::InterfaceTFDecl, py::nodelete>> cls(m, "InterfaceTFDecl");
}
