// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/user_systf.h>

void bind_UserSystf(py::module_& m) {
  py::class_<uhdm::UserSystf, std::unique_ptr<uhdm::UserSystf, py::nodelete>> cls(m, "UserSystf");
}
