// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/array_typespec.h>
#include <uhdm/function.h>
#include <uhdm/range.h>
#include <uhdm/ref_typespec.h>

void bind_ArrayTypespec(py::module_& m) {
  py::class_<uhdm::ArrayTypespec, uhdm::Typespec, std::unique_ptr<uhdm::ArrayTypespec, py::nodelete>> cls(m, "ArrayTypespec");
  cls.def_property_readonly("range", [](uhdm::ArrayTypespec* self) {
    std::vector<uhdm::Range*> res;
    if (auto* vec = self->getRanges()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("index_typespec", [](uhdm::ArrayTypespec* self) { return self->getIndexTypespec(); }, py::return_value_policy::reference);
  cls.def_property_readonly("elem_typespec", [](uhdm::ArrayTypespec* self) { return self->getElemTypespec(); }, py::return_value_policy::reference);
  cls.def_property_readonly("resolution_func", [](uhdm::ArrayTypespec* self) { return self->getResolutionFunc(); }, py::return_value_policy::reference);
  cls.def_property_readonly("packed", &uhdm::ArrayTypespec::getPacked);
}
