// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/net.h>
#include <uhdm/expr.h>
#include <uhdm/net.h>

void bind_Net(py::module_& m) {
  py::class_<uhdm::Net, uhdm::Nets, std::unique_ptr<uhdm::Net, py::nodelete>> cls(m, "Net");
  cls.def_property_readonly("bit", [](uhdm::Net* self) {
    std::vector<uhdm::Net*> res;
    if (auto* vec = self->getBits()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("indexes", [](uhdm::Net* self) {
    std::vector<uhdm::Expr*> res;
    if (auto* vec = self->getIndexes()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
}
