// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/thread_obj.h>

void bind_Thread(py::module_& m) {
  py::class_<uhdm::Thread, std::unique_ptr<uhdm::Thread, py::nodelete>> cls(m, "Thread");
}
