// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/io_decl.h>

void bind_IODecl(py::module_& m) {
  py::class_<uhdm::IODecl, std::unique_ptr<uhdm::IODecl, py::nodelete>> cls(m, "IODecl");
  cls.def_property_readonly("name", &uhdm::IODecl::getName);
  cls.def_property_readonly("scalar", &uhdm::IODecl::getScalar);
  cls.def_property_readonly("vector", &uhdm::IODecl::getVector);
}
