// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/let_expr.h>

void bind_LetExpr(py::module_& m) {
  py::class_<uhdm::LetExpr, uhdm::Expr, std::unique_ptr<uhdm::LetExpr, py::nodelete>> cls(m, "LetExpr");
}
