// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/gen_case.h>

void bind_GenCase(py::module_& m) {
  py::class_<uhdm::GenCase, uhdm::GenStmt, std::unique_ptr<uhdm::GenCase, py::nodelete>> cls(m, "GenCase");
}
