// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/process_stmt.h>

void bind_Process(py::module_& m) {
  py::class_<uhdm::Process, std::unique_ptr<uhdm::Process, py::nodelete>> cls(m, "Process");
}
