// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/constraint.h>
#include <uhdm/attribute.h>

void bind_Constraint(py::module_& m) {
  py::class_<uhdm::Constraint, std::unique_ptr<uhdm::Constraint, py::nodelete>> cls(m, "Constraint");
  cls.def_property_readonly("name", &uhdm::Constraint::getName);
  cls.def_property_readonly("full_name", &uhdm::Constraint::getFullName);
  cls.def_property_readonly("virtual", &uhdm::Constraint::getVirtual);
  cls.def_property_readonly("automatic", &uhdm::Constraint::getAutomatic);
  cls.def_property_readonly("attribute", [](uhdm::Constraint* self) {
    std::vector<uhdm::Attribute*> res;
    if (auto* vec = self->getAttributes()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("is_constraint_enabled", &uhdm::Constraint::getIsConstraintEnabled);
}
