// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/path_term.h>

void bind_PathTerm(py::module_& m) {
  py::class_<uhdm::PathTerm, std::unique_ptr<uhdm::PathTerm, py::nodelete>> cls(m, "PathTerm");
}
