// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/break_stmt.h>

void bind_BreakStmt(py::module_& m) {
  py::class_<uhdm::BreakStmt, uhdm::AtomicStmt, std::unique_ptr<uhdm::BreakStmt, py::nodelete>> cls(m, "BreakStmt");
}
