// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/task.h>

void bind_Task(py::module_& m) {
  py::class_<uhdm::Task, uhdm::TaskFunc, std::unique_ptr<uhdm::Task, py::nodelete>> cls(m, "Task");
}
