// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/modport.h>

void bind_Modport(py::module_& m) {
  py::class_<uhdm::Modport, std::unique_ptr<uhdm::Modport, py::nodelete>> cls(m, "Modport");
}
