// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/task_call.h>

void bind_TaskCall(py::module_& m) {
  py::class_<uhdm::TaskCall, uhdm::TFCall, std::unique_ptr<uhdm::TaskCall, py::nodelete>> cls(m, "TaskCall");
}
