// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/return_stmt.h>

void bind_ReturnStmt(py::module_& m) {
  py::class_<uhdm::ReturnStmt, uhdm::AtomicStmt, std::unique_ptr<uhdm::ReturnStmt, py::nodelete>> cls(m, "ReturnStmt");
}
