// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/waits.h>

void bind_Waits(py::module_& m) {
  py::class_<uhdm::Waits, uhdm::AtomicStmt, std::unique_ptr<uhdm::Waits, py::nodelete>> cls(m, "Waits");
}
