// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/extends.h>

void bind_Extends(py::module_& m) {
  py::class_<uhdm::Extends, std::unique_ptr<uhdm::Extends, py::nodelete>> cls(m, "Extends");
}
