// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/assume.h>

void bind_Assume(py::module_& m) {
  py::class_<uhdm::Assume, uhdm::ConcurrentAssertions, std::unique_ptr<uhdm::Assume, py::nodelete>> cls(m, "Assume");
}
