// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/clocking_block.h>

void bind_ClockingBlock(py::module_& m) {
  py::class_<uhdm::ClockingBlock, uhdm::Scope, std::unique_ptr<uhdm::ClockingBlock, py::nodelete>> cls(m, "ClockingBlock");
}
