// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/table_entry.h>

void bind_TableEntry(py::module_& m) {
  py::class_<uhdm::TableEntry, std::unique_ptr<uhdm::TableEntry, py::nodelete>> cls(m, "TableEntry");
}
