// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/while_stmt.h>

void bind_WhileStmt(py::module_& m) {
  py::class_<uhdm::WhileStmt, uhdm::AtomicStmt, std::unique_ptr<uhdm::WhileStmt, py::nodelete>> cls(m, "WhileStmt");
}
