// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/module.h>
#include <uhdm/alias_stmt.h>
#include <uhdm/clocking_block.h>
#include <uhdm/cont_assign.h>
#include <uhdm/def_param.h>
#include <uhdm/gen_scope_array.h>
#include <uhdm/instance_array.h>
#include <uhdm/interface.h>
#include <uhdm/interface_array.h>
#include <uhdm/io_decl.h>
#include <uhdm/mod_path.h>
#include <uhdm/module.h>
#include <uhdm/module_array.h>
#include <uhdm/port.h>
#include <uhdm/primitive.h>
#include <uhdm/primitive_array.h>
#include <uhdm/process_stmt.h>
#include <uhdm/ref_module.h>
#include <uhdm/tchk.h>
#include <uhdm/tf_call.h>

void bind_Module(py::module_& m) {
  py::class_<uhdm::Module, uhdm::Instance, std::unique_ptr<uhdm::Module, py::nodelete>> cls(m, "Module");
  cls.def_property_readonly("top_module", &uhdm::Module::getTopModule);
  cls.def_property_readonly("global_clocking", [](uhdm::Module* self) { return self->getGlobalClocking(); }, py::return_value_policy::reference);
  cls.def_property_readonly("default_clocking", [](uhdm::Module* self) { return self->getDefaultClocking(); }, py::return_value_policy::reference);
  cls.def_property_readonly("module_array", [](uhdm::Module* self) { return self->getModuleArray(); }, py::return_value_policy::reference);
  cls.def_property_readonly("instance_array", [](uhdm::Module* self) { return self->getInstanceArray(); }, py::return_value_policy::reference);
  cls.def_property_readonly("port", [](uhdm::Module* self) {
    std::vector<uhdm::Port*> res;
    if (auto* vec = self->getPorts()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("interface", [](uhdm::Module* self) {
    std::vector<uhdm::Interface*> res;
    if (auto* vec = self->getInterfaces()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("interface_array", [](uhdm::Module* self) {
    std::vector<uhdm::InterfaceArray*> res;
    if (auto* vec = self->getInterfaceArrays()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("processes", [](uhdm::Module* self) {
    std::vector<uhdm::Process*> res;
    if (auto* vec = self->getProcesses()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("modules", [](uhdm::Module* self) {
    std::vector<uhdm::Module*> res;
    if (auto* vec = self->getModules()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("module_arrays", [](uhdm::Module* self) {
    std::vector<uhdm::ModuleArray*> res;
    if (auto* vec = self->getModuleArrays()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("gen_scope_array", [](uhdm::Module* self) {
    std::vector<uhdm::GenScopeArray*> res;
    if (auto* vec = self->getGenScopeArrays()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("cont_assign", [](uhdm::Module* self) {
    std::vector<uhdm::ContAssign*> res;
    if (auto* vec = self->getContAssigns()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("primitive", [](uhdm::Module* self) {
    std::vector<uhdm::Primitive*> res;
    if (auto* vec = self->getPrimitives()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("primitive_array", [](uhdm::Module* self) {
    std::vector<uhdm::PrimitiveArray*> res;
    if (auto* vec = self->getPrimitiveArrays()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("mod_path", [](uhdm::Module* self) {
    std::vector<uhdm::ModPath*> res;
    if (auto* vec = self->getModPaths()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("tchk", [](uhdm::Module* self) {
    std::vector<uhdm::Tchk*> res;
    if (auto* vec = self->getTchks()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("def_param", [](uhdm::Module* self) {
    std::vector<uhdm::DefParam*> res;
    if (auto* vec = self->getDefParams()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("io_decl", [](uhdm::Module* self) {
    std::vector<uhdm::IODecl*> res;
    if (auto* vec = self->getIODecls()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("aliases", [](uhdm::Module* self) {
    std::vector<uhdm::Alias*> res;
    if (auto* vec = self->getAliases()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("clocking_block", [](uhdm::Module* self) {
    std::vector<uhdm::ClockingBlock*> res;
    if (auto* vec = self->getClockingBlocks()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("sys_task_call", [](uhdm::Module* self) {
    std::vector<uhdm::TFCall*> res;
    if (auto* vec = self->getSysTaskCalls()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("ref_module", [](uhdm::Module* self) {
    std::vector<uhdm::RefModule*> res;
    if (auto* vec = self->getRefModules()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("end_label", &uhdm::Module::getEndLabel);
}
