// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/named_event.h>

void bind_NamedEvent(py::module_& m) {
  py::class_<uhdm::NamedEvent, std::unique_ptr<uhdm::NamedEvent, py::nodelete>> cls(m, "NamedEvent");
  cls.def_property_readonly("array_member", &uhdm::NamedEvent::getArrayMember);
  cls.def_property_readonly("name", &uhdm::NamedEvent::getName);
  cls.def_property_readonly("full_name", &uhdm::NamedEvent::getFullName);
  cls.def_property_readonly("automatic", &uhdm::NamedEvent::getAutomatic);
  cls.def_property_readonly("end_label", &uhdm::NamedEvent::getEndLabel);
}
