// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/part_select.h>

void bind_PartSelect(py::module_& m) {
  py::class_<uhdm::PartSelect, uhdm::RefObj, std::unique_ptr<uhdm::PartSelect, py::nodelete>> cls(m, "PartSelect");
  cls.def_property_readonly("constant_select", &uhdm::PartSelect::getConstantSelect);
}
