// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/interface_typespec.h>

void bind_InterfaceTypespec(py::module_& m) {
  py::class_<uhdm::InterfaceTypespec, uhdm::Typespec, std::unique_ptr<uhdm::InterfaceTypespec, py::nodelete>> cls(m, "InterfaceTypespec");
}
