// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/program.h>
#include <uhdm/clocking_block.h>
#include <uhdm/cont_assign.h>
#include <uhdm/gen_scope_array.h>
#include <uhdm/instance_array.h>
#include <uhdm/interface.h>
#include <uhdm/interface_array.h>
#include <uhdm/port.h>
#include <uhdm/process_stmt.h>

void bind_Program(py::module_& m) {
  py::class_<uhdm::Program, uhdm::Instance, std::unique_ptr<uhdm::Program, py::nodelete>> cls(m, "Program");
  cls.def_property_readonly("default_clocking", [](uhdm::Program* self) { return self->getDefaultClocking(); }, py::return_value_policy::reference);
  cls.def_property_readonly("instance_array", [](uhdm::Program* self) { return self->getInstanceArray(); }, py::return_value_policy::reference);
  cls.def_property_readonly("interface", [](uhdm::Program* self) {
    std::vector<uhdm::Interface*> res;
    if (auto* vec = self->getInterfaces()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("interface_array", [](uhdm::Program* self) {
    std::vector<uhdm::InterfaceArray*> res;
    if (auto* vec = self->getInterfaceArrays()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("processes", [](uhdm::Program* self) {
    std::vector<uhdm::Process*> res;
    if (auto* vec = self->getProcesses()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("cont_assign", [](uhdm::Program* self) {
    std::vector<uhdm::ContAssign*> res;
    if (auto* vec = self->getContAssigns()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("clocking_block", [](uhdm::Program* self) {
    std::vector<uhdm::ClockingBlock*> res;
    if (auto* vec = self->getClockingBlocks()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("port", [](uhdm::Program* self) {
    std::vector<uhdm::Port*> res;
    if (auto* vec = self->getPorts()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("gen_scope_array", [](uhdm::Program* self) {
    std::vector<uhdm::GenScopeArray*> res;
    if (auto* vec = self->getGenScopeArrays()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("end_label", &uhdm::Program::getEndLabel);
}
