// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/sys_task_call.h>

void bind_SysTaskCall(py::module_& m) {
  py::class_<uhdm::SysTaskCall, uhdm::TFCall, std::unique_ptr<uhdm::SysTaskCall, py::nodelete>> cls(m, "SysTaskCall");
  cls.def_property_readonly("user_defn", &uhdm::SysTaskCall::getUserDefn);
}
