// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/gate.h>

void bind_Gate(py::module_& m) {
  py::class_<uhdm::Gate, uhdm::Primitive, std::unique_ptr<uhdm::Gate, py::nodelete>> cls(m, "Gate");
}
