// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/net.h>

void bind_Net(py::module_& m) {
  py::class_<uhdm::Net, uhdm::Nets, std::unique_ptr<uhdm::Net, py::nodelete>> cls(m, "Net");
}
