// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/checker_port.h>

void bind_CheckerPort(py::module_& m) {
  py::class_<uhdm::CheckerPort, uhdm::Ports, std::unique_ptr<uhdm::CheckerPort, py::nodelete>> cls(m, "CheckerPort");
}
