// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/udp_array.h>

void bind_UdpArray(py::module_& m) {
  py::class_<uhdm::UdpArray, uhdm::PrimitiveArray, std::unique_ptr<uhdm::UdpArray, py::nodelete>> cls(m, "UdpArray");
}
