// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/distribution.h>

void bind_Distribution(py::module_& m) {
  py::class_<uhdm::Distribution, uhdm::ConstraintExpr, std::unique_ptr<uhdm::Distribution, py::nodelete>> cls(m, "Distribution");
  cls.def_property_readonly("soft", &uhdm::Distribution::getSoft);
}
