// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/initial.h>

void bind_Initial(py::module_& m) {
  py::class_<uhdm::Initial, uhdm::Process, std::unique_ptr<uhdm::Initial, py::nodelete>> cls(m, "Initial");
}
