// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/repeat_control.h>

void bind_RepeatControl(py::module_& m) {
  py::class_<uhdm::RepeatControl, uhdm::AtomicStmt, std::unique_ptr<uhdm::RepeatControl, py::nodelete>> cls(m, "RepeatControl");
}
