// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/task_func.h>

void bind_TaskFunc(py::module_& m) {
  py::class_<uhdm::TaskFunc, uhdm::Scope, std::unique_ptr<uhdm::TaskFunc, py::nodelete>> cls(m, "TaskFunc");
  cls.def_property_readonly("method", &uhdm::TaskFunc::getMethod);
  cls.def_property_readonly("virtual", &uhdm::TaskFunc::getVirtual);
  cls.def_property_readonly("automatic", &uhdm::TaskFunc::getAutomatic);
  cls.def_property_readonly("dpi_pure", &uhdm::TaskFunc::getDPIPure);
  cls.def_property_readonly("dpi_context", &uhdm::TaskFunc::getDPIContext);
  cls.def_property_readonly("dpi_c_identifier", &uhdm::TaskFunc::getDPICIdentifier);
}
