// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/checker_decl.h>

void bind_CheckerDecl(py::module_& m) {
  py::class_<uhdm::CheckerDecl, uhdm::Instance, std::unique_ptr<uhdm::CheckerDecl, py::nodelete>> cls(m, "CheckerDecl");
}
