// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/property_typespec.h>

void bind_PropertyTypespec(py::module_& m) {
  py::class_<uhdm::PropertyTypespec, uhdm::Typespec, std::unique_ptr<uhdm::PropertyTypespec, py::nodelete>> cls(m, "PropertyTypespec");
}
