// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/source_file.h>

void bind_SourceFile(py::module_& m) {
  py::class_<uhdm::SourceFile, std::unique_ptr<uhdm::SourceFile, py::nodelete>> cls(m, "SourceFile");
  cls.def_property_readonly("name", &uhdm::SourceFile::getName);
}
