// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/cont_assign.h>
#include <uhdm/cont_assign_bit.h>
#include <uhdm/expr.h>

void bind_ContAssign(py::module_& m) {
  py::class_<uhdm::ContAssign, std::unique_ptr<uhdm::ContAssign, py::nodelete>> cls(m, "ContAssign");
  cls.def_property_readonly("net_decl_assign", &uhdm::ContAssign::getNetDeclAssign);
  cls.def_property_readonly("delay", [](uhdm::ContAssign* self) { return self->getDelay(); }, py::return_value_policy::reference);
  cls.def_property_readonly("rhs", [](uhdm::ContAssign* self) { return self->getRhs(); }, py::return_value_policy::reference);
  cls.def_property_readonly("lhs", [](uhdm::ContAssign* self) { return self->getLhs(); }, py::return_value_policy::reference);
  cls.def_property_readonly("bit", [](uhdm::ContAssign* self) {
    std::vector<uhdm::ContAssignBit*> res;
    if (auto* vec = self->getBits()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
}
