// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/chandle_typespec.h>

void bind_ChandleTypespec(py::module_& m) {
  py::class_<uhdm::ChandleTypespec, uhdm::Typespec, std::unique_ptr<uhdm::ChandleTypespec, py::nodelete>> cls(m, "ChandleTypespec");
}
