// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/cont_assign.h>

void bind_ContAssign(py::module_& m) {
  py::class_<uhdm::ContAssign, std::unique_ptr<uhdm::ContAssign, py::nodelete>> cls(m, "ContAssign");
  cls.def_property_readonly("net_decl_assign", &uhdm::ContAssign::getNetDeclAssign);
}
