// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/void_typespec.h>

void bind_VoidTypespec(py::module_& m) {
  py::class_<uhdm::VoidTypespec, uhdm::Typespec, std::unique_ptr<uhdm::VoidTypespec, py::nodelete>> cls(m, "VoidTypespec");
}
