// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/scope.h>

void bind_Scope(py::module_& m) {
  py::class_<uhdm::Scope, std::unique_ptr<uhdm::Scope, py::nodelete>> cls(m, "Scope");
  cls.def_property_readonly("full_name", &uhdm::Scope::getFullName);
}
