// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/immediate_cover.h>
#include <uhdm/clocking_block.h>
#include <uhdm/expr.h>

void bind_ImmediateCover(py::module_& m) {
  py::class_<uhdm::ImmediateCover, uhdm::AtomicStmt, std::unique_ptr<uhdm::ImmediateCover, py::nodelete>> cls(m, "ImmediateCover");
  cls.def_property_readonly("expr", [](uhdm::ImmediateCover* self) { return self->getExpr(); }, py::return_value_policy::reference);
  cls.def_property_readonly("clocking_block", [](uhdm::ImmediateCover* self) { return self->getClockingBlock(); }, py::return_value_policy::reference);
}
