// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/release.h>

void bind_Release(py::module_& m) {
  py::class_<uhdm::Release, uhdm::AtomicStmt, std::unique_ptr<uhdm::Release, py::nodelete>> cls(m, "Release");
}
