// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/case_stmt.h>

void bind_CaseStmt(py::module_& m) {
  py::class_<uhdm::CaseStmt, uhdm::AtomicStmt, std::unique_ptr<uhdm::CaseStmt, py::nodelete>> cls(m, "CaseStmt");
}
