// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/checker_inst.h>

void bind_CheckerInst(py::module_& m) {
  py::class_<uhdm::CheckerInst, uhdm::Instance, std::unique_ptr<uhdm::CheckerInst, py::nodelete>> cls(m, "CheckerInst");
}
