// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/do_while.h>

void bind_DoWhile(py::module_& m) {
  py::class_<uhdm::DoWhile, uhdm::AtomicStmt, std::unique_ptr<uhdm::DoWhile, py::nodelete>> cls(m, "DoWhile");
}
