// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/case_property.h>
#include <uhdm/case_property_item.h>
#include <uhdm/expr.h>

void bind_CaseProperty(py::module_& m) {
  py::class_<uhdm::CaseProperty, std::unique_ptr<uhdm::CaseProperty, py::nodelete>> cls(m, "CaseProperty");
  cls.def_property_readonly("condition", [](uhdm::CaseProperty* self) { return self->getCondition(); }, py::return_value_policy::reference);
  cls.def_property_readonly("case_property_item", [](uhdm::CaseProperty* self) {
    std::vector<uhdm::CasePropertyItem*> res;
    if (auto* vec = self->getCasePropertyItems()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
}
