// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/module_array.h>

void bind_ModuleArray(py::module_& m) {
  py::class_<uhdm::ModuleArray, uhdm::InstanceArray, std::unique_ptr<uhdm::ModuleArray, py::nodelete>> cls(m, "ModuleArray");
}
