// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/spec_param.h>

void bind_SpecParam(py::module_& m) {
  py::class_<uhdm::SpecParam, uhdm::SimpleExpr, std::unique_ptr<uhdm::SpecParam, py::nodelete>> cls(m, "SpecParam");
}
