// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/part_select.h>
#include <uhdm/expr.h>

void bind_PartSelect(py::module_& m) {
  py::class_<uhdm::PartSelect, uhdm::RefObj, std::unique_ptr<uhdm::PartSelect, py::nodelete>> cls(m, "PartSelect");
  cls.def_property_readonly("constant_select", &uhdm::PartSelect::getConstantSelect);
  cls.def_property_readonly("left_expr", [](uhdm::PartSelect* self) { return self->getLeftExpr(); }, py::return_value_policy::reference);
  cls.def_property_readonly("right_expr", [](uhdm::PartSelect* self) { return self->getRightExpr(); }, py::return_value_policy::reference);
}
