// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/struct_pattern.h>

void bind_StructPattern(py::module_& m) {
  py::class_<uhdm::StructPattern, std::unique_ptr<uhdm::StructPattern, py::nodelete>> cls(m, "StructPattern");
  cls.def_property_readonly("name", &uhdm::StructPattern::getName);
}
