// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/program.h>

void bind_Program(py::module_& m) {
  py::class_<uhdm::Program, uhdm::Instance, std::unique_ptr<uhdm::Program, py::nodelete>> cls(m, "Program");
  cls.def_property_readonly("end_label", &uhdm::Program::getEndLabel);
}
