// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/import_typespec.h>
#include <uhdm/constant.h>
#include <uhdm/identifier.h>

void bind_ImportTypespec(py::module_& m) {
  py::class_<uhdm::ImportTypespec, uhdm::Typespec, std::unique_ptr<uhdm::ImportTypespec, py::nodelete>> cls(m, "ImportTypespec");
  cls.def_property_readonly("name", [](uhdm::ImportTypespec* self) { return self->getName(); }, py::return_value_policy::reference);
  cls.def_property_readonly("item", [](uhdm::ImportTypespec* self) { return self->getItem(); }, py::return_value_policy::reference);
}
