// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/deassign.h>

void bind_Deassign(py::module_& m) {
  py::class_<uhdm::Deassign, uhdm::AtomicStmt, std::unique_ptr<uhdm::Deassign, py::nodelete>> cls(m, "Deassign");
}
