// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/final_stmt.h>

void bind_FinalStmt(py::module_& m) {
  py::class_<uhdm::FinalStmt, uhdm::Process, std::unique_ptr<uhdm::FinalStmt, py::nodelete>> cls(m, "FinalStmt");
}
