// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/attribute.h>

void bind_Attribute(py::module_& m) {
  py::class_<uhdm::Attribute, std::unique_ptr<uhdm::Attribute, py::nodelete>> cls(m, "Attribute");
  cls.def_property_readonly("name", &uhdm::Attribute::getName);
  cls.def_property_readonly("def_attribute", &uhdm::Attribute::getDefAttribute);
  cls.def_property_readonly("def_file", &uhdm::Attribute::getDefFile);
}
