// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/gate_array.h>

void bind_GateArray(py::module_& m) {
  py::class_<uhdm::GateArray, uhdm::PrimitiveArray, std::unique_ptr<uhdm::GateArray, py::nodelete>> cls(m, "GateArray");
}
