// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/constraint_expr.h>

void bind_ConstraintExpr(py::module_& m) {
  py::class_<uhdm::ConstraintExpr, std::unique_ptr<uhdm::ConstraintExpr, py::nodelete>> cls(m, "ConstraintExpr");
}
