// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/net_loads.h>

void bind_NetLoads(py::module_& m) {
  py::class_<uhdm::NetLoads, std::unique_ptr<uhdm::NetLoads, py::nodelete>> cls(m, "NetLoads");
}
