// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/distribution.h>
#include <uhdm/dist_item.h>
#include <uhdm/expr.h>

void bind_Distribution(py::module_& m) {
  py::class_<uhdm::Distribution, uhdm::ConstraintExpr, std::unique_ptr<uhdm::Distribution, py::nodelete>> cls(m, "Distribution");
  cls.def_property_readonly("soft", &uhdm::Distribution::getSoft);
  cls.def_property_readonly("dist_item", [](uhdm::Distribution* self) {
    std::vector<uhdm::DistItem*> res;
    if (auto* vec = self->getDistItems()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("expr", [](uhdm::Distribution* self) { return self->getExpr(); }, py::return_value_policy::reference);
}
