// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/logic_typespec.h>

void bind_LogicTypespec(py::module_& m) {
  py::class_<uhdm::LogicTypespec, uhdm::Typespec, std::unique_ptr<uhdm::LogicTypespec, py::nodelete>> cls(m, "LogicTypespec");
  cls.def_property_readonly("signed", &uhdm::LogicTypespec::getSigned);
}
