// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/bit_typespec.h>

void bind_BitTypespec(py::module_& m) {
  py::class_<uhdm::BitTypespec, uhdm::Typespec, std::unique_ptr<uhdm::BitTypespec, py::nodelete>> cls(m, "BitTypespec");
  cls.def_property_readonly("signed", &uhdm::BitTypespec::getSigned);
}
