// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/unsupported_expr.h>

void bind_UnsupportedExpr(py::module_& m) {
  py::class_<uhdm::UnsupportedExpr, uhdm::Expr, std::unique_ptr<uhdm::UnsupportedExpr, py::nodelete>> cls(m, "UnsupportedExpr");
}
