// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/immediate_cover.h>

void bind_ImmediateCover(py::module_& m) {
  py::class_<uhdm::ImmediateCover, uhdm::AtomicStmt, std::unique_ptr<uhdm::ImmediateCover, py::nodelete>> cls(m, "ImmediateCover");
}
