// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/clocked_property.h>

void bind_ClockedProperty(py::module_& m) {
  py::class_<uhdm::ClockedProperty, std::unique_ptr<uhdm::ClockedProperty, py::nodelete>> cls(m, "ClockedProperty");
}
