// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/primitive_array.h>

void bind_PrimitiveArray(py::module_& m) {
  py::class_<uhdm::PrimitiveArray, uhdm::InstanceArray, std::unique_ptr<uhdm::PrimitiveArray, py::nodelete>> cls(m, "PrimitiveArray");
}
