// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/struct_typespec.h>

void bind_StructTypespec(py::module_& m) {
  py::class_<uhdm::StructTypespec, uhdm::Typespec, std::unique_ptr<uhdm::StructTypespec, py::nodelete>> cls(m, "StructTypespec");
  cls.def_property_readonly("packed", &uhdm::StructTypespec::getPacked);
}
