// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/clocking_io_decl.h>

void bind_ClockingIODecl(py::module_& m) {
  py::class_<uhdm::ClockingIODecl, std::unique_ptr<uhdm::ClockingIODecl, py::nodelete>> cls(m, "ClockingIODecl");
}
