// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/assign_stmt.h>
#include <uhdm/expr.h>

void bind_AssignStmt(py::module_& m) {
  py::class_<uhdm::AssignStmt, uhdm::AtomicStmt, std::unique_ptr<uhdm::AssignStmt, py::nodelete>> cls(m, "AssignStmt");
  cls.def_property_readonly("rhs", [](uhdm::AssignStmt* self) { return self->getRhs(); }, py::return_value_policy::reference);
  cls.def_property_readonly("lhs", [](uhdm::AssignStmt* self) { return self->getLhs(); }, py::return_value_policy::reference);
}
