// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/type_parameter.h>

void bind_TypeParameter(py::module_& m) {
  py::class_<uhdm::TypeParameter, uhdm::Typespec, std::unique_ptr<uhdm::TypeParameter, py::nodelete>> cls(m, "TypeParameter");
  cls.def_property_readonly("name", &uhdm::TypeParameter::getName);
  cls.def_property_readonly("full_name", &uhdm::TypeParameter::getFullName);
  cls.def_property_readonly("local_param", &uhdm::TypeParameter::getLocalParam);
  cls.def_property_readonly("imported", &uhdm::TypeParameter::getImported);
}
