// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/nets.h>

void bind_Nets(py::module_& m) {
  py::class_<uhdm::Nets, uhdm::SimpleExpr, std::unique_ptr<uhdm::Nets, py::nodelete>> cls(m, "Nets");
  cls.def_property_readonly("array_member", &uhdm::Nets::getArrayMember);
  cls.def_property_readonly("constant_select", &uhdm::Nets::getConstantSelect);
  cls.def_property_readonly("expanded", &uhdm::Nets::getExpanded);
  cls.def_property_readonly("implicit_decl", &uhdm::Nets::getImplicitDecl);
  cls.def_property_readonly("name", &uhdm::Nets::getName);
  cls.def_property_readonly("full_name", &uhdm::Nets::getFullName);
  cls.def_property_readonly("net_decl_assign", &uhdm::Nets::getNetDeclAssign);
  cls.def_property_readonly("scalar", &uhdm::Nets::getScalar);
  cls.def_property_readonly("explicit_scalared", &uhdm::Nets::getExplicitScalared);
  cls.def_property_readonly("vector", &uhdm::Nets::getVector);
  cls.def_property_readonly("explicit_vectored", &uhdm::Nets::getExplicitVectored);
  cls.def_property_readonly("struct_union_member", &uhdm::Nets::getStructUnionMember);
}
