// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/short_real_typespec.h>

void bind_ShortRealTypespec(py::module_& m) {
  py::class_<uhdm::ShortRealTypespec, uhdm::Typespec, std::unique_ptr<uhdm::ShortRealTypespec, py::nodelete>> cls(m, "ShortRealTypespec");
}
