// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/constr_foreach.h>

void bind_ConstrForeach(py::module_& m) {
  py::class_<uhdm::ConstrForeach, uhdm::ConstraintExpr, std::unique_ptr<uhdm::ConstrForeach, py::nodelete>> cls(m, "ConstrForeach");
}
