// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/assignment.h>

void bind_Assignment(py::module_& m) {
  py::class_<uhdm::Assignment, uhdm::AtomicStmt, std::unique_ptr<uhdm::Assignment, py::nodelete>> cls(m, "Assignment");
  cls.def_property_readonly("blocking", &uhdm::Assignment::getBlocking);
}
