// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/case_property_item.h>

void bind_CasePropertyItem(py::module_& m) {
  py::class_<uhdm::CasePropertyItem, std::unique_ptr<uhdm::CasePropertyItem, py::nodelete>> cls(m, "CasePropertyItem");
}
