// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/def_param.h>

void bind_DefParam(py::module_& m) {
  py::class_<uhdm::DefParam, std::unique_ptr<uhdm::DefParam, py::nodelete>> cls(m, "DefParam");
}
