// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/reg_array.h>
#include <uhdm/expr.h>
#include <uhdm/reg.h>

void bind_RegArray(py::module_& m) {
  py::class_<uhdm::RegArray, std::unique_ptr<uhdm::RegArray, py::nodelete>> cls(m, "RegArray");
  cls.def_property_readonly("is_memory", &uhdm::RegArray::getIsMemory);
  cls.def_property_readonly("left_expr", [](uhdm::RegArray* self) { return self->getLeftExpr(); }, py::return_value_policy::reference);
  cls.def_property_readonly("right_expr", [](uhdm::RegArray* self) { return self->getRightExpr(); }, py::return_value_policy::reference);
  cls.def_property_readonly("memory_word", [](uhdm::RegArray* self) {
    std::vector<uhdm::Reg*> res;
    if (auto* vec = self->getMemoryWords()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
}
