// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/concurrent_assertions.h>

void bind_ConcurrentAssertions(py::module_& m) {
  py::class_<uhdm::ConcurrentAssertions, std::unique_ptr<uhdm::ConcurrentAssertions, py::nodelete>> cls(m, "ConcurrentAssertions");
  cls.def_property_readonly("name", &uhdm::ConcurrentAssertions::getName);
  cls.def_property_readonly("full_name", &uhdm::ConcurrentAssertions::getFullName);
  cls.def_property_readonly("is_clock_inferred", &uhdm::ConcurrentAssertions::getIsClockInferred);
}
