// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/property_spec.h>

void bind_PropertySpec(py::module_& m) {
  py::class_<uhdm::PropertySpec, std::unique_ptr<uhdm::PropertySpec, py::nodelete>> cls(m, "PropertySpec");
}
