// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/sys_func_call.h>

void bind_SysFuncCall(py::module_& m) {
  py::class_<uhdm::SysFuncCall, uhdm::TFCall, std::unique_ptr<uhdm::SysFuncCall, py::nodelete>> cls(m, "SysFuncCall");
  cls.def_property_readonly("user_defn", &uhdm::SysFuncCall::getUserDefn);
}
