// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/parameter.h>

void bind_Parameter(py::module_& m) {
  py::class_<uhdm::Parameter, uhdm::SimpleExpr, std::unique_ptr<uhdm::Parameter, py::nodelete>> cls(m, "Parameter");
  cls.def_property_readonly("local_param", &uhdm::Parameter::getLocalParam);
  cls.def_property_readonly("name", &uhdm::Parameter::getName);
  cls.def_property_readonly("full_name", &uhdm::Parameter::getFullName);
  cls.def_property_readonly("imported", &uhdm::Parameter::getImported);
}
