// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/tchk.h>

void bind_Tchk(py::module_& m) {
  py::class_<uhdm::Tchk, std::unique_ptr<uhdm::Tchk, py::nodelete>> cls(m, "Tchk");
}
