// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/case_property.h>

void bind_CaseProperty(py::module_& m) {
  py::class_<uhdm::CaseProperty, std::unique_ptr<uhdm::CaseProperty, py::nodelete>> cls(m, "CaseProperty");
}
