// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/implication.h>
#include <uhdm/constraint_expr.h>
#include <uhdm/expr.h>

void bind_Implication(py::module_& m) {
  py::class_<uhdm::Implication, uhdm::ConstraintExpr, std::unique_ptr<uhdm::Implication, py::nodelete>> cls(m, "Implication");
  cls.def_property_readonly("condition", [](uhdm::Implication* self) { return self->getCondition(); }, py::return_value_policy::reference);
  cls.def_property_readonly("constraint_expr", [](uhdm::Implication* self) {
    std::vector<uhdm::ConstraintExpr*> res;
    if (auto* vec = self->getConstraintExprs()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
}
