// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/forever_stmt.h>

void bind_ForeverStmt(py::module_& m) {
  py::class_<uhdm::ForeverStmt, uhdm::AtomicStmt, std::unique_ptr<uhdm::ForeverStmt, py::nodelete>> cls(m, "ForeverStmt");
}
