// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/source_file.h>
#include <uhdm/comment.h>
#include <uhdm/preproc_macro_definition.h>
#include <uhdm/preproc_macro_instance.h>
#include <uhdm/source_file.h>

void bind_SourceFile(py::module_& m) {
  py::class_<uhdm::SourceFile, std::unique_ptr<uhdm::SourceFile, py::nodelete>> cls(m, "SourceFile");
  cls.def_property_readonly("name", &uhdm::SourceFile::getName);
  cls.def_property_readonly("includes", [](uhdm::SourceFile* self) {
    std::vector<uhdm::SourceFile*> res;
    if (auto* vec = self->getIncludes()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("preproc_macro_definition", [](uhdm::SourceFile* self) {
    std::vector<uhdm::PreprocMacroDefinition*> res;
    if (auto* vec = self->getPreprocMacroDefinitions()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("preproc_macro_instance", [](uhdm::SourceFile* self) {
    std::vector<uhdm::PreprocMacroInstance*> res;
    if (auto* vec = self->getPreprocMacroInstances()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("comment", [](uhdm::SourceFile* self) {
    std::vector<uhdm::Comment*> res;
    if (auto* vec = self->getComments()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
}
