// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/tf_call.h>

void bind_TFCall(py::module_& m) {
  py::class_<uhdm::TFCall, uhdm::Expr, std::unique_ptr<uhdm::TFCall, py::nodelete>> cls(m, "TFCall");
}
