// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/preproc_macro_definition.h>

void bind_PreprocMacroDefinition(py::module_& m) {
  py::class_<uhdm::PreprocMacroDefinition, std::unique_ptr<uhdm::PreprocMacroDefinition, py::nodelete>> cls(m, "PreprocMacroDefinition");
  cls.def_property_readonly("name", &uhdm::PreprocMacroDefinition::getName);
}
