// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/function_decl.h>

void bind_FunctionDecl(py::module_& m) {
  py::class_<uhdm::FunctionDecl, uhdm::TaskFuncDecl, std::unique_ptr<uhdm::FunctionDecl, py::nodelete>> cls(m, "FunctionDecl");
}
