// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/wait_stmt.h>

void bind_WaitStmt(py::module_& m) {
  py::class_<uhdm::WaitStmt, uhdm::Waits, std::unique_ptr<uhdm::WaitStmt, py::nodelete>> cls(m, "WaitStmt");
}
