// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/task_decl.h>

void bind_TaskDecl(py::module_& m) {
  py::class_<uhdm::TaskDecl, uhdm::TaskFuncDecl, std::unique_ptr<uhdm::TaskDecl, py::nodelete>> cls(m, "TaskDecl");
}
