// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/property_decl.h>

void bind_PropertyDecl(py::module_& m) {
  py::class_<uhdm::PropertyDecl, std::unique_ptr<uhdm::PropertyDecl, py::nodelete>> cls(m, "PropertyDecl");
  cls.def_property_readonly("name", &uhdm::PropertyDecl::getName);
  cls.def_property_readonly("full_name", &uhdm::PropertyDecl::getFullName);
}
