// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/reg.h>

void bind_Reg(py::module_& m) {
  py::class_<uhdm::Reg, std::unique_ptr<uhdm::Reg, py::nodelete>> cls(m, "Reg");
}
