// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/range.h>

void bind_Range(py::module_& m) {
  py::class_<uhdm::Range, std::unique_ptr<uhdm::Range, py::nodelete>> cls(m, "Range");
}
