// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/instance.h>

void bind_Instance(py::module_& m) {
  py::class_<uhdm::Instance, uhdm::Scope, std::unique_ptr<uhdm::Instance, py::nodelete>> cls(m, "Instance");
  cls.def_property_readonly("def_name", &uhdm::Instance::getDefName);
  cls.def_property_readonly("array_member", &uhdm::Instance::getArrayMember);
  cls.def_property_readonly("cell_instance", &uhdm::Instance::getCellInstance);
  cls.def_property_readonly("def_file", &uhdm::Instance::getDefFile);
  cls.def_property_readonly("protected", &uhdm::Instance::getProtected);
  cls.def_property_readonly("library", &uhdm::Instance::getLibrary);
  cls.def_property_readonly("cell", &uhdm::Instance::getCell);
  cls.def_property_readonly("config", &uhdm::Instance::getConfig);
  cls.def_property_readonly("automatic", &uhdm::Instance::getAutomatic);
  cls.def_property_readonly("top", &uhdm::Instance::getTop);
}
