// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/typespec_member.h>
#include <uhdm/expr.h>
#include <uhdm/ref_typespec.h>

void bind_TypespecMember(py::module_& m) {
  py::class_<uhdm::TypespecMember, std::unique_ptr<uhdm::TypespecMember, py::nodelete>> cls(m, "TypespecMember");
  cls.def_property_readonly("name", &uhdm::TypespecMember::getName);
  cls.def_property_readonly("rand_type", &uhdm::TypespecMember::getRandType);
  cls.def_property_readonly("typespec", [](uhdm::TypespecMember* self) { return self->getTypespec(); }, py::return_value_policy::reference);
  cls.def_property_readonly("default_value", [](uhdm::TypespecMember* self) { return self->getDefaultValue(); }, py::return_value_policy::reference);
}
