// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/ref_obj.h>

void bind_RefObj(py::module_& m) {
  py::class_<uhdm::RefObj, uhdm::SimpleExpr, std::unique_ptr<uhdm::RefObj, py::nodelete>> cls(m, "RefObj");
  cls.def_property_readonly("name", &uhdm::RefObj::getName);
  cls.def_property_readonly("full_name", &uhdm::RefObj::getFullName);
  cls.def_property_readonly("def_name", &uhdm::RefObj::getDefName);
  cls.def_property_readonly("generic", &uhdm::RefObj::getGeneric);
  cls.def_property_readonly("struct_member", &uhdm::RefObj::getStructMember);
}
