// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/class_obj.h>
#include <uhdm/constraint.h>
#include <uhdm/expr.h>
#include <uhdm/ref_typespec.h>
#include <uhdm/task_func.h>
#include <uhdm/thread_obj.h>

void bind_ClassObj(py::module_& m) {
  py::class_<uhdm::ClassObj, uhdm::Scope, std::unique_ptr<uhdm::ClassObj, py::nodelete>> cls(m, "ClassObj");
  cls.def_property_readonly("class_typespec", [](uhdm::ClassObj* self) { return self->getClassTypespec(); }, py::return_value_policy::reference);
  cls.def_property_readonly("threads", [](uhdm::ClassObj* self) {
    std::vector<uhdm::Thread*> res;
    if (auto* vec = self->getThreads()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("messages", [](uhdm::ClassObj* self) {
    std::vector<uhdm::Expr*> res;
    if (auto* vec = self->getMessages()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("task_func", [](uhdm::ClassObj* self) {
    std::vector<uhdm::TaskFunc*> res;
    if (auto* vec = self->getTaskFuncs()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("constraint", [](uhdm::ClassObj* self) {
    std::vector<uhdm::Constraint*> res;
    if (auto* vec = self->getConstraints()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
}
