// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/net_drivers.h>

void bind_NetDrivers(py::module_& m) {
  py::class_<uhdm::NetDrivers, std::unique_ptr<uhdm::NetDrivers, py::nodelete>> cls(m, "NetDrivers");
}
