// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/property_decl.h>
#include <uhdm/attribute.h>
#include <uhdm/prop_formal_decl.h>
#include <uhdm/property_spec.h>
#include <uhdm/variable.h>

void bind_PropertyDecl(py::module_& m) {
  py::class_<uhdm::PropertyDecl, std::unique_ptr<uhdm::PropertyDecl, py::nodelete>> cls(m, "PropertyDecl");
  cls.def_property_readonly("name", &uhdm::PropertyDecl::getName);
  cls.def_property_readonly("full_name", &uhdm::PropertyDecl::getFullName);
  cls.def_property_readonly("attribute", [](uhdm::PropertyDecl* self) {
    std::vector<uhdm::Attribute*> res;
    if (auto* vec = self->getAttributes()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("prop_formal_decl", [](uhdm::PropertyDecl* self) {
    std::vector<uhdm::PropFormalDecl*> res;
    if (auto* vec = self->getPropFormalDecls()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("variable", [](uhdm::PropertyDecl* self) {
    std::vector<uhdm::Variable*> res;
    if (auto* vec = self->getVariables()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("property_spec", [](uhdm::PropertyDecl* self) { return self->getPropertySpec(); }, py::return_value_policy::reference);
}
