// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/seq_formal_decl.h>

void bind_SeqFormalDecl(py::module_& m) {
  py::class_<uhdm::SeqFormalDecl, std::unique_ptr<uhdm::SeqFormalDecl, py::nodelete>> cls(m, "SeqFormalDecl");
  cls.def_property_readonly("name", &uhdm::SeqFormalDecl::getName);
}
