// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/indexed_part_select.h>

void bind_IndexedPartSelect(py::module_& m) {
  py::class_<uhdm::IndexedPartSelect, uhdm::RefObj, std::unique_ptr<uhdm::IndexedPartSelect, py::nodelete>> cls(m, "IndexedPartSelect");
  cls.def_property_readonly("constant_select", &uhdm::IndexedPartSelect::getConstantSelect);
}
