// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/union_typespec.h>
#include <uhdm/typespec_member.h>

void bind_UnionTypespec(py::module_& m) {
  py::class_<uhdm::UnionTypespec, uhdm::Typespec, std::unique_ptr<uhdm::UnionTypespec, py::nodelete>> cls(m, "UnionTypespec");
  cls.def_property_readonly("packed", &uhdm::UnionTypespec::getPacked);
  cls.def_property_readonly("tagged", &uhdm::UnionTypespec::getTagged);
  cls.def_property_readonly("member", [](uhdm::UnionTypespec* self) {
    std::vector<uhdm::TypespecMember*> res;
    if (auto* vec = self->getMembers()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
}
