// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/comment.h>

void bind_Comment(py::module_& m) {
  py::class_<uhdm::Comment, std::unique_ptr<uhdm::Comment, py::nodelete>> cls(m, "Comment");
  cls.def_property_readonly("name", &uhdm::Comment::getName);
}
