// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/operation.h>

void bind_Operation(py::module_& m) {
  py::class_<uhdm::Operation, uhdm::Expr, std::unique_ptr<uhdm::Operation, py::nodelete>> cls(m, "Operation");
  cls.def_property_readonly("reordered", &uhdm::Operation::getReordered);
  cls.def_property_readonly("flattened", &uhdm::Operation::getFlattened);
  cls.def_property_readonly("op_strong", &uhdm::Operation::getOpStrong);
}
