// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/atomic_stmt.h>

void bind_AtomicStmt(py::module_& m) {
  py::class_<uhdm::AtomicStmt, std::unique_ptr<uhdm::AtomicStmt, py::nodelete>> cls(m, "AtomicStmt");
  cls.def_property_readonly("label", &uhdm::AtomicStmt::getLabel);
}
