// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/port_bit.h>

void bind_PortBit(py::module_& m) {
  py::class_<uhdm::PortBit, uhdm::Ports, std::unique_ptr<uhdm::PortBit, py::nodelete>> cls(m, "PortBit");
}
