// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/delay_control.h>

void bind_DelayControl(py::module_& m) {
  py::class_<uhdm::DelayControl, uhdm::AtomicStmt, std::unique_ptr<uhdm::DelayControl, py::nodelete>> cls(m, "DelayControl");
}
