// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/time_typespec.h>

void bind_TimeTypespec(py::module_& m) {
  py::class_<uhdm::TimeTypespec, uhdm::Typespec, std::unique_ptr<uhdm::TimeTypespec, py::nodelete>> cls(m, "TimeTypespec");
}
