// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/param_assign.h>

void bind_ParamAssign(py::module_& m) {
  py::class_<uhdm::ParamAssign, std::unique_ptr<uhdm::ParamAssign, py::nodelete>> cls(m, "ParamAssign");
  cls.def_property_readonly("conn_by_name", &uhdm::ParamAssign::getConnByName);
  cls.def_property_readonly("overriden", &uhdm::ParamAssign::getOverriden);
}
