// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/sequence_inst.h>

void bind_SequenceInst(py::module_& m) {
  py::class_<uhdm::SequenceInst, std::unique_ptr<uhdm::SequenceInst, py::nodelete>> cls(m, "SequenceInst");
  cls.def_property_readonly("name", &uhdm::SequenceInst::getName);
}
