// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/ref_module.h>
#include <uhdm/port.h>

void bind_RefModule(py::module_& m) {
  py::class_<uhdm::RefModule, std::unique_ptr<uhdm::RefModule, py::nodelete>> cls(m, "RefModule");
  cls.def_property_readonly("name", &uhdm::RefModule::getName);
  cls.def_property_readonly("def_name", &uhdm::RefModule::getDefName);
  cls.def_property_readonly("port", [](uhdm::RefModule* self) {
    std::vector<uhdm::Port*> res;
    if (auto* vec = self->getPorts()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
}
