// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/implication.h>

void bind_Implication(py::module_& m) {
  py::class_<uhdm::Implication, uhdm::ConstraintExpr, std::unique_ptr<uhdm::Implication, py::nodelete>> cls(m, "Implication");
}
