// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/primitive.h>

void bind_Primitive(py::module_& m) {
  py::class_<uhdm::Primitive, std::unique_ptr<uhdm::Primitive, py::nodelete>> cls(m, "Primitive");
  cls.def_property_readonly("array_member", &uhdm::Primitive::getArrayMember);
  cls.def_property_readonly("def_name", &uhdm::Primitive::getDefName);
  cls.def_property_readonly("name", &uhdm::Primitive::getName);
  cls.def_property_readonly("full_name", &uhdm::Primitive::getFullName);
}
