// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/gen_case.h>
#include <uhdm/case_item.h>
#include <uhdm/expr.h>

void bind_GenCase(py::module_& m) {
  py::class_<uhdm::GenCase, uhdm::GenStmt, std::unique_ptr<uhdm::GenCase, py::nodelete>> cls(m, "GenCase");
  cls.def_property_readonly("condition", [](uhdm::GenCase* self) { return self->getCondition(); }, py::return_value_policy::reference);
  cls.def_property_readonly("case_item", [](uhdm::GenCase* self) {
    std::vector<uhdm::CaseItem*> res;
    if (auto* vec = self->getCaseItems()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
}
