// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/mod_path.h>

void bind_ModPath(py::module_& m) {
  py::class_<uhdm::ModPath, std::unique_ptr<uhdm::ModPath, py::nodelete>> cls(m, "ModPath");
}
