// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/int_typespec.h>

void bind_IntTypespec(py::module_& m) {
  py::class_<uhdm::IntTypespec, uhdm::Typespec, std::unique_ptr<uhdm::IntTypespec, py::nodelete>> cls(m, "IntTypespec");
  cls.def_property_readonly("signed", &uhdm::IntTypespec::getSigned);
}
