// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/long_int_typespec.h>

void bind_LongIntTypespec(py::module_& m) {
  py::class_<uhdm::LongIntTypespec, uhdm::Typespec, std::unique_ptr<uhdm::LongIntTypespec, py::nodelete>> cls(m, "LongIntTypespec");
  cls.def_property_readonly("signed", &uhdm::LongIntTypespec::getSigned);
}
