// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/assign_stmt.h>

void bind_AssignStmt(py::module_& m) {
  py::class_<uhdm::AssignStmt, uhdm::AtomicStmt, std::unique_ptr<uhdm::AssignStmt, py::nodelete>> cls(m, "AssignStmt");
}
