// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/class_obj.h>

void bind_ClassObj(py::module_& m) {
  py::class_<uhdm::ClassObj, uhdm::Scope, std::unique_ptr<uhdm::ClassObj, py::nodelete>> cls(m, "ClassObj");
}
