// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/enum_typespec.h>

void bind_EnumTypespec(py::module_& m) {
  py::class_<uhdm::EnumTypespec, uhdm::Typespec, std::unique_ptr<uhdm::EnumTypespec, py::nodelete>> cls(m, "EnumTypespec");
}
