// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/tagged_pattern.h>

void bind_TaggedPattern(py::module_& m) {
  py::class_<uhdm::TaggedPattern, std::unique_ptr<uhdm::TaggedPattern, py::nodelete>> cls(m, "TaggedPattern");
  cls.def_property_readonly("name", &uhdm::TaggedPattern::getName);
}
