// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/gen_if.h>

void bind_GenIf(py::module_& m) {
  py::class_<uhdm::GenIf, uhdm::GenStmt, std::unique_ptr<uhdm::GenIf, py::nodelete>> cls(m, "GenIf");
}
