// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/array_typespec.h>

void bind_ArrayTypespec(py::module_& m) {
  py::class_<uhdm::ArrayTypespec, uhdm::Typespec, std::unique_ptr<uhdm::ArrayTypespec, py::nodelete>> cls(m, "ArrayTypespec");
  cls.def_property_readonly("packed", &uhdm::ArrayTypespec::getPacked);
}
