// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/sequence_typespec.h>

void bind_SequenceTypespec(py::module_& m) {
  py::class_<uhdm::SequenceTypespec, uhdm::Typespec, std::unique_ptr<uhdm::SequenceTypespec, py::nodelete>> cls(m, "SequenceTypespec");
}
