// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/prim_term.h>

void bind_PrimTerm(py::module_& m) {
  py::class_<uhdm::PrimTerm, std::unique_ptr<uhdm::PrimTerm, py::nodelete>> cls(m, "PrimTerm");
}
