// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/always.h>

void bind_Always(py::module_& m) {
  py::class_<uhdm::Always, uhdm::Process, std::unique_ptr<uhdm::Always, py::nodelete>> cls(m, "Always");
}
