// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/port.h>

void bind_Port(py::module_& m) {
  py::class_<uhdm::Port, uhdm::Ports, std::unique_ptr<uhdm::Port, py::nodelete>> cls(m, "Port");
}
