// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/array_expr.h>

void bind_ArrayExpr(py::module_& m) {
  py::class_<uhdm::ArrayExpr, uhdm::Expr, std::unique_ptr<uhdm::ArrayExpr, py::nodelete>> cls(m, "ArrayExpr");
}
