// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/import_typespec.h>

void bind_ImportTypespec(py::module_& m) {
  py::class_<uhdm::ImportTypespec, uhdm::Typespec, std::unique_ptr<uhdm::ImportTypespec, py::nodelete>> cls(m, "ImportTypespec");
}
