// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/struct_typespec.h>
#include <uhdm/function.h>
#include <uhdm/typespec_member.h>

void bind_StructTypespec(py::module_& m) {
  py::class_<uhdm::StructTypespec, uhdm::Typespec, std::unique_ptr<uhdm::StructTypespec, py::nodelete>> cls(m, "StructTypespec");
  cls.def_property_readonly("packed", &uhdm::StructTypespec::getPacked);
  cls.def_property_readonly("member", [](uhdm::StructTypespec* self) {
    std::vector<uhdm::TypespecMember*> res;
    if (auto* vec = self->getMembers()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("resolution_func", [](uhdm::StructTypespec* self) { return self->getResolutionFunc(); }, py::return_value_policy::reference);
}
