// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/property_inst.h>

void bind_PropertyInst(py::module_& m) {
  py::class_<uhdm::PropertyInst, std::unique_ptr<uhdm::PropertyInst, py::nodelete>> cls(m, "PropertyInst");
  cls.def_property_readonly("name", &uhdm::PropertyInst::getName);
}
