// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/sequence_decl.h>

void bind_SequenceDecl(py::module_& m) {
  py::class_<uhdm::SequenceDecl, std::unique_ptr<uhdm::SequenceDecl, py::nodelete>> cls(m, "SequenceDecl");
  cls.def_property_readonly("name", &uhdm::SequenceDecl::getName);
  cls.def_property_readonly("full_name", &uhdm::SequenceDecl::getFullName);
}
