// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/interface_typespec.h>
#include <uhdm/identifier.h>
#include <uhdm/interface.h>
#include <uhdm/modport.h>
#include <uhdm/param_assign.h>

void bind_InterfaceTypespec(py::module_& m) {
  py::class_<uhdm::InterfaceTypespec, uhdm::Typespec, std::unique_ptr<uhdm::InterfaceTypespec, py::nodelete>> cls(m, "InterfaceTypespec");
  cls.def_property_readonly("name", [](uhdm::InterfaceTypespec* self) { return self->getName(); }, py::return_value_policy::reference);
  cls.def_property_readonly("modport", [](uhdm::InterfaceTypespec* self) { return self->getModport(); }, py::return_value_policy::reference);
  cls.def_property_readonly("param_assign", [](uhdm::InterfaceTypespec* self) {
    std::vector<uhdm::ParamAssign*> res;
    if (auto* vec = self->getParamAssigns()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("interface", [](uhdm::InterfaceTypespec* self) { return self->getInterface(); }, py::return_value_policy::reference);
}
