// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/switch_tran.h>

void bind_SwitchTran(py::module_& m) {
  py::class_<uhdm::SwitchTran, uhdm::Primitive, std::unique_ptr<uhdm::SwitchTran, py::nodelete>> cls(m, "SwitchTran");
}
