// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/design.h>

void bind_Design(py::module_& m) {
  py::class_<uhdm::Design, std::unique_ptr<uhdm::Design, py::nodelete>> cls(m, "Design");
  cls.def_property_readonly("elaborated", &uhdm::Design::getElaborated);
  cls.def_property_readonly("name", &uhdm::Design::getName);
}
