// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/constr_if.h>

void bind_ConstrIf(py::module_& m) {
  py::class_<uhdm::ConstrIf, uhdm::ConstraintExpr, std::unique_ptr<uhdm::ConstrIf, py::nodelete>> cls(m, "ConstrIf");
}
