// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/interface.h>

void bind_Interface(py::module_& m) {
  py::class_<uhdm::Interface, uhdm::Instance, std::unique_ptr<uhdm::Interface, py::nodelete>> cls(m, "Interface");
  cls.def_property_readonly("end_label", &uhdm::Interface::getEndLabel);
}
