// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/event_control.h>

void bind_EventControl(py::module_& m) {
  py::class_<uhdm::EventControl, uhdm::AtomicStmt, std::unique_ptr<uhdm::EventControl, py::nodelete>> cls(m, "EventControl");
}
