// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/atomic_stmt.h>
#include <uhdm/attribute.h>

void bind_AtomicStmt(py::module_& m) {
  py::class_<uhdm::AtomicStmt, std::unique_ptr<uhdm::AtomicStmt, py::nodelete>> cls(m, "AtomicStmt");
  cls.def_property_readonly("label", &uhdm::AtomicStmt::getLabel);
  cls.def_property_readonly("attribute", [](uhdm::AtomicStmt* self) {
    std::vector<uhdm::Attribute*> res;
    if (auto* vec = self->getAttributes()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
}
