// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/soft_disable.h>

void bind_SoftDisable(py::module_& m) {
  py::class_<uhdm::SoftDisable, uhdm::ConstraintExpr, std::unique_ptr<uhdm::SoftDisable, py::nodelete>> cls(m, "SoftDisable");
}
