// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/constant.h>

void bind_Constant(py::module_& m) {
  py::class_<uhdm::Constant, uhdm::Expr, std::unique_ptr<uhdm::Constant, py::nodelete>> cls(m, "Constant");
}
