// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/constraint_ordering.h>

void bind_ConstraintOrdering(py::module_& m) {
  py::class_<uhdm::ConstraintOrdering, std::unique_ptr<uhdm::ConstraintOrdering, py::nodelete>> cls(m, "ConstraintOrdering");
}
