// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/checker_inst_port.h>
#include <uhdm/property_inst.h>
#include <uhdm/sequence_inst.h>

void bind_CheckerInstPort(py::module_& m) {
  py::class_<uhdm::CheckerInstPort, std::unique_ptr<uhdm::CheckerInstPort, py::nodelete>> cls(m, "CheckerInstPort");
  cls.def_property_readonly("property_inst", [](uhdm::CheckerInstPort* self) { return self->getPropertyInst(); }, py::return_value_policy::reference);
  cls.def_property_readonly("sequence_inst", [](uhdm::CheckerInstPort* self) { return self->getSequenceInst(); }, py::return_value_policy::reference);
}
