// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/ref_module.h>

void bind_RefModule(py::module_& m) {
  py::class_<uhdm::RefModule, std::unique_ptr<uhdm::RefModule, py::nodelete>> cls(m, "RefModule");
  cls.def_property_readonly("name", &uhdm::RefModule::getName);
  cls.def_property_readonly("def_name", &uhdm::RefModule::getDefName);
}
