// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/udp_defn.h>

void bind_UdpDefn(py::module_& m) {
  py::class_<uhdm::UdpDefn, uhdm::Scope, std::unique_ptr<uhdm::UdpDefn, py::nodelete>> cls(m, "UdpDefn");
  cls.def_property_readonly("def_name", &uhdm::UdpDefn::getDefName);
  cls.def_property_readonly("protected", &uhdm::UdpDefn::getProtected);
}
