// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/typedef_typespec.h>

void bind_TypedefTypespec(py::module_& m) {
  py::class_<uhdm::TypedefTypespec, uhdm::Typespec, std::unique_ptr<uhdm::TypedefTypespec, py::nodelete>> cls(m, "TypedefTypespec");
}
