// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/class_typespec.h>

void bind_ClassTypespec(py::module_& m) {
  py::class_<uhdm::ClassTypespec, uhdm::Typespec, std::unique_ptr<uhdm::ClassTypespec, py::nodelete>> cls(m, "ClassTypespec");
  cls.def_property_readonly("name", &uhdm::ClassTypespec::getName);
  cls.def_property_readonly("automatic", &uhdm::ClassTypespec::getAutomatic);
}
