// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/class_defn.h>

void bind_ClassDefn(py::module_& m) {
  py::class_<uhdm::ClassDefn, uhdm::Scope, std::unique_ptr<uhdm::ClassDefn, py::nodelete>> cls(m, "ClassDefn");
  cls.def_property_readonly("virtual", &uhdm::ClassDefn::getVirtual);
  cls.def_property_readonly("automatic", &uhdm::ClassDefn::getAutomatic);
  cls.def_property_readonly("end_label", &uhdm::ClassDefn::getEndLabel);
}
