// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/case_item.h>

void bind_CaseItem(py::module_& m) {
  py::class_<uhdm::CaseItem, std::unique_ptr<uhdm::CaseItem, py::nodelete>> cls(m, "CaseItem");
}
