// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/foreach_stmt.h>

void bind_ForeachStmt(py::module_& m) {
  py::class_<uhdm::ForeachStmt, uhdm::Scope, std::unique_ptr<uhdm::ForeachStmt, py::nodelete>> cls(m, "ForeachStmt");
}
