// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/expect_stmt.h>

void bind_ExpectStmt(py::module_& m) {
  py::class_<uhdm::ExpectStmt, uhdm::AtomicStmt, std::unique_ptr<uhdm::ExpectStmt, py::nodelete>> cls(m, "ExpectStmt");
}
