// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/clocked_seq.h>

void bind_ClockedSeq(py::module_& m) {
  py::class_<uhdm::ClockedSeq, std::unique_ptr<uhdm::ClockedSeq, py::nodelete>> cls(m, "ClockedSeq");
}
