// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/force.h>

void bind_Force(py::module_& m) {
  py::class_<uhdm::Force, uhdm::AtomicStmt, std::unique_ptr<uhdm::Force, py::nodelete>> cls(m, "Force");
}
