// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/gen_scope_array.h>

void bind_GenScopeArray(py::module_& m) {
  py::class_<uhdm::GenScopeArray, std::unique_ptr<uhdm::GenScopeArray, py::nodelete>> cls(m, "GenScopeArray");
  cls.def_property_readonly("name", &uhdm::GenScopeArray::getName);
  cls.def_property_readonly("full_name", &uhdm::GenScopeArray::getFullName);
}
