// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/checker_decl.h>
#include <uhdm/checker_port.h>
#include <uhdm/clocking_block.h>
#include <uhdm/cont_assign.h>
#include <uhdm/process_stmt.h>

void bind_CheckerDecl(py::module_& m) {
  py::class_<uhdm::CheckerDecl, uhdm::Instance, std::unique_ptr<uhdm::CheckerDecl, py::nodelete>> cls(m, "CheckerDecl");
  cls.def_property_readonly("default_clocking", [](uhdm::CheckerDecl* self) { return self->getDefaultClocking(); }, py::return_value_policy::reference);
  cls.def_property_readonly("processes", [](uhdm::CheckerDecl* self) {
    std::vector<uhdm::Process*> res;
    if (auto* vec = self->getProcesses()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("cont_assign", [](uhdm::CheckerDecl* self) {
    std::vector<uhdm::ContAssign*> res;
    if (auto* vec = self->getContAssigns()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("port", [](uhdm::CheckerDecl* self) {
    std::vector<uhdm::CheckerPort*> res;
    if (auto* vec = self->getPorts()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
}
