// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/switch_array.h>

void bind_SwitchArray(py::module_& m) {
  py::class_<uhdm::SwitchArray, uhdm::PrimitiveArray, std::unique_ptr<uhdm::SwitchArray, py::nodelete>> cls(m, "SwitchArray");
}
