// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/identifier.h>

void bind_Identifier(py::module_& m) {
  py::class_<uhdm::Identifier, std::unique_ptr<uhdm::Identifier, py::nodelete>> cls(m, "Identifier");
  cls.def_property_readonly("name", &uhdm::Identifier::getName);
}
