// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/unsupported_stmt.h>

void bind_UnsupportedStmt(py::module_& m) {
  py::class_<uhdm::UnsupportedStmt, uhdm::AtomicStmt, std::unique_ptr<uhdm::UnsupportedStmt, py::nodelete>> cls(m, "UnsupportedStmt");
}
