// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/var_select.h>

void bind_VarSelect(py::module_& m) {
  py::class_<uhdm::VarSelect, uhdm::RefObj, std::unique_ptr<uhdm::VarSelect, py::nodelete>> cls(m, "VarSelect");
  cls.def_property_readonly("constant_select", &uhdm::VarSelect::getConstantSelect);
}
