// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/modport.h>
#include <uhdm/identifier.h>
#include <uhdm/interface.h>
#include <uhdm/io_decl.h>

void bind_Modport(py::module_& m) {
  py::class_<uhdm::Modport, std::unique_ptr<uhdm::Modport, py::nodelete>> cls(m, "Modport");
  cls.def_property_readonly("name", [](uhdm::Modport* self) { return self->getName(); }, py::return_value_policy::reference);
  cls.def_property_readonly("io_decl", [](uhdm::Modport* self) {
    std::vector<uhdm::IODecl*> res;
    if (auto* vec = self->getIODecls()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
  cls.def_property_readonly("interface", [](uhdm::Modport* self) { return self->getInterface(); }, py::return_value_policy::reference);
}
