// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/unsupported_typespec.h>
#include <uhdm/range.h>

void bind_UnsupportedTypespec(py::module_& m) {
  py::class_<uhdm::UnsupportedTypespec, uhdm::Typespec, std::unique_ptr<uhdm::UnsupportedTypespec, py::nodelete>> cls(m, "UnsupportedTypespec");
  cls.def_property_readonly("name", &uhdm::UnsupportedTypespec::getName);
  cls.def_property_readonly("packed", &uhdm::UnsupportedTypespec::getPacked);
  cls.def_property_readonly("range", [](uhdm::UnsupportedTypespec* self) {
    std::vector<uhdm::Range*> res;
    if (auto* vec = self->getRanges()) {
      res.reserve(vec->size());
      res.insert(res.end(), vec->begin(), vec->end());
    }
    return res;
  }, py::return_value_policy::reference);
}
