// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/reg_array.h>

void bind_RegArray(py::module_& m) {
  py::class_<uhdm::RegArray, std::unique_ptr<uhdm::RegArray, py::nodelete>> cls(m, "RegArray");
  cls.def_property_readonly("is_memory", &uhdm::RegArray::getIsMemory);
}
