// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/instance_array.h>

void bind_InstanceArray(py::module_& m) {
  py::class_<uhdm::InstanceArray, std::unique_ptr<uhdm::InstanceArray, py::nodelete>> cls(m, "InstanceArray");
  cls.def_property_readonly("name", &uhdm::InstanceArray::getName);
  cls.def_property_readonly("full_name", &uhdm::InstanceArray::getFullName);
}
