// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/package.h>

void bind_Package(py::module_& m) {
  py::class_<uhdm::Package, uhdm::Instance, std::unique_ptr<uhdm::Package, py::nodelete>> cls(m, "Package");
  cls.def_property_readonly("unit", &uhdm::Package::getUnit);
  cls.def_property_readonly("end_label", &uhdm::Package::getEndLabel);
}
