// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/event_typespec.h>

void bind_EventTypespec(py::module_& m) {
  py::class_<uhdm::EventTypespec, uhdm::Typespec, std::unique_ptr<uhdm::EventTypespec, py::nodelete>> cls(m, "EventTypespec");
}
