// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/restrict.h>

void bind_Restrict(py::module_& m) {
  py::class_<uhdm::Restrict, uhdm::ConcurrentAssertions, std::unique_ptr<uhdm::Restrict, py::nodelete>> cls(m, "Restrict");
}
