// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/cont_assign_bit.h>

void bind_ContAssignBit(py::module_& m) {
  py::class_<uhdm::ContAssignBit, std::unique_ptr<uhdm::ContAssignBit, py::nodelete>> cls(m, "ContAssignBit");
  cls.def_property_readonly("net_decl_assign", &uhdm::ContAssignBit::getNetDeclAssign);
}
