// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/assert_stmt.h>

void bind_Assert(py::module_& m) {
  py::class_<uhdm::Assert, uhdm::ConcurrentAssertions, std::unique_ptr<uhdm::Assert, py::nodelete>> cls(m, "Assert");
}
