// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/short_int_typespec.h>

void bind_ShortIntTypespec(py::module_& m) {
  py::class_<uhdm::ShortIntTypespec, uhdm::Typespec, std::unique_ptr<uhdm::ShortIntTypespec, py::nodelete>> cls(m, "ShortIntTypespec");
  cls.def_property_readonly("signed", &uhdm::ShortIntTypespec::getSigned);
}
