// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/null_stmt.h>

void bind_NullStmt(py::module_& m) {
  py::class_<uhdm::NullStmt, uhdm::AtomicStmt, std::unique_ptr<uhdm::NullStmt, py::nodelete>> cls(m, "NullStmt");
}
