// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/typespec_member.h>

void bind_TypespecMember(py::module_& m) {
  py::class_<uhdm::TypespecMember, std::unique_ptr<uhdm::TypespecMember, py::nodelete>> cls(m, "TypespecMember");
  cls.def_property_readonly("name", &uhdm::TypespecMember::getName);
  cls.def_property_readonly("rand_type", &uhdm::TypespecMember::getRandType);
}
