// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/wait_fork.h>

void bind_WaitFork(py::module_& m) {
  py::class_<uhdm::WaitFork, uhdm::Waits, std::unique_ptr<uhdm::WaitFork, py::nodelete>> cls(m, "WaitFork");
}
