// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/expr.h>

void bind_Expr(py::module_& m) {
  py::class_<uhdm::Expr, std::unique_ptr<uhdm::Expr, py::nodelete>> cls(m, "Expr");
  cls.def_property_readonly("decompile", &uhdm::Expr::getDecompile);
}
