// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/udp.h>

void bind_Udp(py::module_& m) {
  py::class_<uhdm::Udp, uhdm::Primitive, std::unique_ptr<uhdm::Udp, py::nodelete>> cls(m, "Udp");
}
