// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/variable.h>

void bind_Variable(py::module_& m) {
  py::class_<uhdm::Variable, uhdm::SimpleExpr, std::unique_ptr<uhdm::Variable, py::nodelete>> cls(m, "Variable");
  cls.def_property_readonly("array_member", &uhdm::Variable::getArrayMember);
  cls.def_property_readonly("name", &uhdm::Variable::getName);
  cls.def_property_readonly("full_name", &uhdm::Variable::getFullName);
  cls.def_property_readonly("automatic", &uhdm::Variable::getAutomatic);
  cls.def_property_readonly("constant_variable", &uhdm::Variable::getConstantVariable);
  cls.def_property_readonly("is_randomized", &uhdm::Variable::getIsRandomized);
  cls.def_property_readonly("struct_union_member", &uhdm::Variable::getStructUnionMember);
  cls.def_property_readonly("scalar", &uhdm::Variable::getScalar);
  cls.def_property_readonly("vector", &uhdm::Variable::getVector);
}
