// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/any_pattern.h>

void bind_AnyPattern(py::module_& m) {
  py::class_<uhdm::AnyPattern, std::unique_ptr<uhdm::AnyPattern, py::nodelete>> cls(m, "AnyPattern");
  cls.def_property_readonly("name", &uhdm::AnyPattern::getName);
}
