// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/simple_expr.h>

void bind_SimpleExpr(py::module_& m) {
  py::class_<uhdm::SimpleExpr, uhdm::Expr, std::unique_ptr<uhdm::SimpleExpr, py::nodelete>> cls(m, "SimpleExpr");
}
