// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/hier_path.h>

void bind_HierPath(py::module_& m) {
  py::class_<uhdm::HierPath, uhdm::SimpleExpr, std::unique_ptr<uhdm::HierPath, py::nodelete>> cls(m, "HierPath");
  cls.def_property_readonly("name", &uhdm::HierPath::getName);
  cls.def_property_readonly("full_name", &uhdm::HierPath::getFullName);
}
