// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/disable_fork.h>

void bind_DisableFork(py::module_& m) {
  py::class_<uhdm::DisableFork, uhdm::Disables, std::unique_ptr<uhdm::DisableFork, py::nodelete>> cls(m, "DisableFork");
}
