// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/ports.h>

void bind_Ports(py::module_& m) {
  py::class_<uhdm::Ports, std::unique_ptr<uhdm::Ports, py::nodelete>> cls(m, "Ports");
  cls.def_property_readonly("name", &uhdm::Ports::getName);
  cls.def_property_readonly("scalar", &uhdm::Ports::getScalar);
  cls.def_property_readonly("vector", &uhdm::Ports::getVector);
  cls.def_property_readonly("conn_by_name", &uhdm::Ports::getConnByName);
  cls.def_property_readonly("explicit_name", &uhdm::Ports::getExplicitName);
}
