// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/typespec.h>

void bind_Typespec(py::module_& m) {
  py::class_<uhdm::Typespec, std::unique_ptr<uhdm::Typespec, py::nodelete>> cls(m, "Typespec");
}
