// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/gen_region.h>

void bind_GenRegion(py::module_& m) {
  py::class_<uhdm::GenRegion, uhdm::GenScope, std::unique_ptr<uhdm::GenRegion, py::nodelete>> cls(m, "GenRegion");
}
