// AUTOGENERATED POC - DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
namespace py = pybind11;

#include <uhdm/func_call.h>

void bind_FuncCall(py::module_& m) {
  py::class_<uhdm::FuncCall, uhdm::TFCall, std::unique_ptr<uhdm::FuncCall, py::nodelete>> cls(m, "FuncCall");
}
