sudo: required

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"


before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get install build-essential tclsh
  
install:

# Build steps
script:
  - sed -i 's/nestingLimit = 64/nestingLimit = 1024/g' third_party/capnproto/c++/src/capnp/message.h
  - sed -i 's/8 \* 1024 \* 1024/64 \* 1024 \* 1024 \* 1024/g' third_party/capnproto/c++/src/capnp/message.h
  - make clean
  - make
  - make test
  - sudo make install
  - make test_install
  
  