sudo: required

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"


before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get install build-essential tclsh
  
install:

# Build steps
script:
  - make clean
  - make
  - make test
  - sudo make install
  - make test_install
  
  