sudo: required

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - build-essential
            - tclsh

      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"


before_install:
  - eval "${MATRIX_EVAL}"

install:

# Build steps
script:
  - cmake --version
  - make clean
  - make
  - make test
  - sudo make install
  - make test_install
