sudo: required

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc
  
before_install:
  - sudo apt-get install build-essential tclsh
  - curl -O https://capnproto.org/capnproto-c++-0.7.0.tar.gz
  - tar zxf capnproto-c++-0.7.0.tar.gz
  - cd capnproto-c++-0.7.0
  - ./configure
  - make -j 
  - sudo make install
  
install:

# Build steps
script:
  - cd ../UHDM
  - make clean
  - make
  