/*
 Do not modify, auto-generated by cloner.py

 Copyright 2019-2020 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   Cloner.cpp
 * Author: hs
 *
 * Created on July 14, 2023, 00:00 AM
 */
#include <uhdm/Cloner.h>
#include <uhdm/uhdm.h>

namespace UHDM {
template <typename T>
inline T* Cloner::cloneT(const T* source, any* parent) {
  if (source == nullptr) return nullptr;
  T* const target = m_serializer->Clone(source);
  target->VpiParent(parent);
  copy(source, target);
  return target;
}

// clang-format off
void Cloner::copy(const any* source, any* target) {}

//<COPY_IMPLEMENTATIONS>
// clang-format on

// clang-format off
any* Cloner::clone(const any* source, any* parent) { return cloneAny(source, parent); }
//<CLONE_ANY_IMPLEMENTATIONS>
// clang-format on

// clang-format off
VectorOfany* Cloner::clone(const VectorOfany* source, any* parent) { return cloneT<any>(source, parent); }
//<CLONE_MANY_IMPLEMENTATIONS>
// clang-format on

any* Cloner::cloneAny(const any* source, any* parent) {
  if (source == nullptr) return nullptr;

  m_callstack.emplace_back(source);
  any* target = nullptr;

  // clang-format off
  switch (source->UhdmType()) {
//<CLONE_ANY_CASE_STATEMENTS>
    default: break;
  }
  // clang-format on

  m_callstack.pop_back();
  return target;
}

any* PassThroughCloner::cloneAny(const any* source, any* parent) {
  return const_cast<any*>(source);
}

// clang-format off
//<PASSTHROUGHCLONER_MANY_IMPLEMENTATIONS>
// clang-format on

any* MirrorCloner::cloneAny(const any* source, any* parent) {
  cloned_t::const_iterator it = m_cloned.find(source);
  if (it != m_cloned.cend()) return it->second;

  any* const target = Cloner::cloneAny(source, parent);
  if (target == nullptr) return nullptr;

  m_cloned.emplace(source, target);
  return target;
}
}  // namespace UHDM
