// -*- c++ -*-

/*
 Do not modify, auto-generated by cloner.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   Cloner.h
 * Author: hs
 *
 * Created on July 14, 2023, 00:00 AM
 */
#ifndef UHDM_CLONER_H
#define UHDM_CLONER_H

#include <uhdm/RTTI.h>
#include <uhdm/Serializer.h>
#include <uhdm/containers.h>

namespace UHDM {
class Cloner : public RTTI {
  UHDM_IMPLEMENT_RTTI(Cloner, RTTI)

 protected:
  using callstack_t = std::vector<const any *>;

 public:
  explicit Cloner(Serializer *serializer) : m_serializer(serializer) {}
  virtual ~Cloner() = default;
  Cloner(const Cloner &rhs) = delete;
  Cloner &operator=(const Cloner &rhs) = delete;

  Serializer *getSerializer() { return m_serializer; }

  template <typename T>
  T *clone(const T *source, any *parent) {
    return static_cast<T *>(cloneAny(static_cast<const any *>(source), parent));
  }

 private:
  template <typename T>
  T *cloneT(const T *source, any *parent);

  template <typename T>
  std::vector<T *> *cloneT(const std::vector<T *> *source, any *parent);

 protected:
  any *cloneAny(const any *source, any *parent);

  // clang-format off
  virtual void copy(const any* source, any* target);
//<COPY_DECLARATIONS>
  // clang-format on

  // clang-format off
  virtual any* clone(const any* source, any* parent);
//<CLONE_ANY_DECLARATIONS>
  // clang-format on

  // clang-format off
  virtual VectorOfany* clone(const VectorOfany* source, any* parent);
//<CLONE_MANY_DECLARATIONS>
  // clang-format on

 protected:
  Serializer *const m_serializer = nullptr;
  callstack_t m_callstack;
};

class PassThroughCloner : public Cloner {
  UHDM_IMPLEMENT_RTTI(PassThroughCloner, Cloner)

 public:
  explicit PassThroughCloner(Serializer *serializer) : Cloner(serializer) {}
  ~PassThroughCloner() override = default;
  PassThroughCloner(const PassThroughCloner &rhs) = delete;
  PassThroughCloner &operator=(const PassThroughCloner &rhs) = delete;

  using Cloner::clone;

 protected:
  // clang-format off
  any *clone(const any *source, any *parent) override { return const_cast<any *>(source); }
//<PASSTHROUGHCLONER_ANY_FUNCTIONS>
  // clang-format on

  // clang-format off
  VectorOfany* clone(const VectorOfany* source, any* parent) override { return const_cast<VectorOfany *>(source); }
//<PASSTHROUGHCLONER_MANY_FUNCTIONS>
  // clang-format on

 private:
  template <typename T>
  T *cloneT(const T *source, any *parent);

  template <typename T>
  std::vector<T *> *cloneT(const std::vector<T *> *source, any *parent);
};
}  // namespace UHDM

UHDM_IMPLEMENT_RTTI_CAST_FUNCTIONS(cloner_cast, UHDM::Cloner)
#endif  // UHDM_CLONER_H
