/*
 Do not modify, auto-generated by script

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   <GROUPNAME>.cpp
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */
#include <uhdm/<GROUPNAME>.h>

#include <uhdm/uhdm_types.h>
#include <uhdm/BaseClass.h>
#include <uhdm/Serializer.h>

namespace uhdm {
bool <GROUPNAME>GroupCompliant(const Any* item) {
  if (item == nullptr) {
    return true;
  }
  UhdmType uhdmType = item->getUhdmType();
  if (<CHECKTYPE>) {
    std::string message;
    message
      .append("Internal Error(")
      .append(std::to_string(item->getUhdmId()))
      .append(") : adding wrong object type (")
      .append(UhdmName(uhdmType))
      .append(") in a <GROUPNAME> group!");
    item->getSerializer()->getErrorHandler()(ErrorType::UHDM_WRONG_OBJECT_TYPE,
                                             message, item, nullptr);
    return false;
  }
  return true;
}

bool <GROUPNAME>GroupCompliant(const AnyCollection* vec) {
  if (vec != nullptr) {
    for (auto item : *vec) {
      if (!<GROUPNAME>GroupCompliant(item)) {
        return false;
      }
    }
  }
  return true;
}

}  // namespace uhdm
