// -*- c++ -*-

/*
 Do not modify, auto-generated by cloner.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   Reducer.h
 * Author: hs
 *
 * Created on November 07, 2024, 00:00 AM
 */
#ifndef UHDM_REDUCER_H
#define UHDM_REDUCER_H

#include <uhdm/containers.h>
#include <uhdm/Serializer.h>

#include <string>
#include <string_view>

namespace UHDM {
class Serializer;

class Reducer final {
 public:
  explicit Reducer(Serializer *serializer) : m_serializer(serializer) {}
  ~Reducer() = default;

  void reduce();

 protected:
  void reduceArray_expr(array_expr* object);
  void reduceOperation(operation* object);

 public:
  Serializer* const m_serializer;
  expr* reduceExpr(any* expr, bool& invalidValue,
                         scope* component, any* compileDesign,
                         scope* instance, 
                         uint32_t lineNumber, any* pexpr,
                         bool muteErrors = false);

  any* getValue(std::string_view name, scope* component,
                      any* compileDesign, 
                      scope* instance, uint32_t lineNumber,
                      any* pexpr, bool muteErrors = false);

  std::pair<task_func*, scope*> getTaskFunc(std::string_view name,
                                                      scope* component,
                                                      any* compileDesign,
                                                      scope* instance,
                                                      any* pexpr);

  any* getObject(std::string_view name, scope* component,
                       any* compileDesign, scope* instance,
                       const any* pexpr);

  void setRange(constant* c, uint16_t lr, uint16_t rr);

 private:
  Reducer(const Reducer &rhs) = delete;
  Reducer &operator=(const Reducer &rhs) = delete;

  template<typename T>
  T* getNamedObject(const std::deque<T*>& objects, std::string_view name);

  template <typename T>
  T* getParentOfType(any* object);

  design* getDesign(std::string_view name);
  package* getPackage(std::string_view name);

  bool loopDetected(uint32_t lineNumber,
                    any* compileDesign, scope* instance);
  expr* getComplexValue(scope* scope, std::string_view name) const;

  module_inst* m_exprEvalPlaceHolder = nullptr;
  std::map<const any*, any*> m_swaps;
  design* m_design = nullptr;
  bool m_unwind = false;
  bool m_checkForLoops = false;
  uint32_t m_stackLevel = 0;
};
}  // namespace UHDM

#endif  // UHDM_REDUCER_H
