/*
 Do not modify, auto-generated by script

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   Serializer.cpp
 * Author:
 *
 * Created on October 4, 2021, 10:53 PM
 */
#include <uhdm/Serializer.h>
#include <uhdm/UhdmListener.h>
#include <uhdm/uhdm.h>
#include <uhdm/vpi_visitor.h>

#include <algorithm>
#include <iomanip>
#include <iostream>
#include <map>
#include <string>
#include <vector>

namespace UHDM {

const uint32_t Serializer::kVersion = 1;

void Serializer::GarbageCollect() {
  if (!m_enableGC) return;

  UhdmListener* const listener = new UhdmListener();
  for (auto d : designMaker.objects_) {
    listener->listenDesign(d);
  }

  const AnySet visited(listener->getVisited().begin(),
                       listener->getVisited().end());
  delete listener;

<FACTORY_GC>
}

void DefaultErrorHandler(ErrorType errType, const std::string& errorMsg,
                         const any* object1, const any* object2) {
  std::cerr << errorMsg << std::endl;
}

SymbolId Serializer::MakeSymbol(std::string_view symbol) {
  return symbolMaker.Make(symbol);
}

std::string_view Serializer::GetSymbol(SymbolId id) const {
  return symbolMaker.GetSymbol(id);
}

SymbolId Serializer::GetSymbolId(std::string_view symbol) const {
  return symbolMaker.GetId(symbol);
}

vpiHandle Serializer::MakeUhdmHandle(UHDM_OBJECT_TYPE type,
                                     const void* object) {
  return uhdm_handleMaker.Make(type, object);
}

Serializer::IdMap Serializer::AllObjects() const {
  IdMap idMap;
<CAPNP_ID>
  return idMap;
}

std::string UhdmName(UHDM_OBJECT_TYPE type) {
  switch (type) {
<UHDM_NAME_MAP>
    default: return "NO TYPE";
  }
}

// From uhdm_types.h
std::string VpiTypeName(vpiHandle h) {
  uhdm_handle* handle = (uhdm_handle*)h;
  BaseClass* obj = (BaseClass*)handle->object;
  return UhdmName(obj->UhdmType());
}

std::map<std::string, uint32_t, std::less<>> Serializer::ObjectStats() const {
  std::map<std::string, uint32_t, std::less<>> stats;
<FACTORY_STATS>
  return stats;
}

void Serializer::PrintStats(std::ostream& strm,
                            std::string_view infoText) const {
  strm << "=== UHDM Object Stats Begin (" << infoText << ") ===" << std::endl;
  auto stats = ObjectStats();
  std::vector<std::string_view> names;
  names.reserve(stats.size());
  std::transform(stats.begin(), stats.end(), std::back_inserter(names),
                 [](decltype(stats)::value_type const& pair) {
                   return std::string_view(pair.first);
                 });
  std::sort(names.begin(), names.end());
  for (std::string_view name : names) {
    auto it = stats.find(name);
    if (it->second > 0) {
      // The longest model name is
      // "enum_struct_union_packed_array_typespec_group"
      strm << std::setw(48) << std::left << name << std::setw(8) << std::right
           << it->second << std::endl;
    }
  }
  strm << "=== UHDM Object Stats End ===" << std::endl;
}

bool Serializer::Erase(const BaseClass* p) {
  if (p == nullptr) {
    return true;
  }

  switch (p->UhdmType()) {
<FACTORY_ERASE_OBJECT>
    default: return false;
  }
}

Serializer::~Serializer() { Purge(); }

void Serializer::Purge() {
  anyVectMaker.Purge();
  symbolMaker.Purge();
  uhdm_handleMaker.Purge();
<FACTORY_PURGE>
}

#ifndef SWIG
void Serializer::PushScope(any* s) { m_scopeStack.emplace_back(s); }
bool Serializer::PopScope(any* s) {
  if (!m_scopeStack.empty() && (m_scopeStack.back() == s)) {
    m_scopeStack.pop_back();
    return true;
  }
  return false;
}

ScopedScope::ScopedScope(any* s) : m_any(s) {
  m_any->GetSerializer()->PushScope(s);
}

ScopedScope::~ScopedScope() { m_any->GetSerializer()->PopScope(m_any); }
#endif

bool BaseClass::SetVpiParent(any* parent, bool force /* = false */) {
#define COLLECT(parentObject, typedObject, getset, maker) \
  auto* collection = parentObject->getset();              \
  if (collection == nullptr) {                            \
    collection = serializer->maker();                     \
    parentObject->getset(collection);                     \
  }                                                       \
  collection->emplace_back(typedObject);

  if (this == parent) return false;
  if (VpiParent() == parent) return true;
  if ((VpiParent() != nullptr) && !force) return false;

  Serializer* const serializer = GetSerializer();
  scope* parentAsScope = any_cast<scope>(parent);
  design* parentAsDesign = any_cast<design>(parent);
  udp_defn* parentAsUdpDefn = any_cast<udp_defn>(parent);

  any* goodParent = nullptr;
  if (parentAsScope != nullptr) {
    goodParent = parentAsScope;
  } else if (parentAsDesign != nullptr) {
    goodParent = parentAsDesign;
  } else if (parentAsUdpDefn != nullptr) {
    goodParent = parentAsUdpDefn;
  } else if (any* const stackTop = serializer->TopScope()) {
    parentAsScope = any_cast<scope>(stackTop);
    parentAsDesign = any_cast<design>(stackTop);
    parentAsUdpDefn = any_cast<udp_defn>(stackTop);
    if (parentAsScope != nullptr) {
      goodParent = parentAsScope;
    } else if (parentAsDesign != nullptr) {
      goodParent = parentAsDesign;
    } else if (parentAsUdpDefn != nullptr) {
      goodParent = parentAsUdpDefn;
    }
  }
  if (goodParent == nullptr) goodParent = parent;
  if (this == goodParent) return false;
  if (VpiParent() == goodParent) return true;

  if (property_decl* const objPropertyDecl = any_cast<property_decl>(this)) {
    if (parentAsScope != nullptr) {
      COLLECT(parentAsScope, objPropertyDecl, Property_decls,
              MakeProperty_declVec);
    }
  } else if (sequence_decl* const objSequenceDecl =
                 any_cast<sequence_decl>(this)) {
    if (parentAsScope != nullptr) {
      COLLECT(parentAsScope, objSequenceDecl, Sequence_decls,
              MakeSequence_declVec);
    }
  } else if (concurrent_assertions* const objConcurrentAssertions =
                 any_cast<concurrent_assertions>(this)) {
    if (parentAsScope != nullptr) {
      COLLECT(parentAsScope, objConcurrentAssertions, Concurrent_assertions,
              MakeConcurrent_assertionsVec);
    }
  } else if (named_event* const objNamedEvent = any_cast<named_event>(this)) {
    if (parentAsScope != nullptr) {
      COLLECT(parentAsScope, objNamedEvent, Named_events, MakeNamed_eventVec);
    }
  } else if (named_event_array* const objNamedEventArray =
                 any_cast<named_event_array>(this)) {
    if (parentAsScope != nullptr) {
      COLLECT(parentAsScope, objNamedEventArray, Named_event_arrays,
              MakeNamed_event_arrayVec);
    }
  } else if (variables* const objVariables = any_cast<variables>(this)) {
    if (parentAsScope != nullptr) {
      COLLECT(parentAsScope, objVariables, Variables, MakeVariablesVec);
      if (logic_var* const objLogicVar = any_cast<logic_var>(objVariables)) {
        COLLECT(parentAsScope, objLogicVar, Logic_vars, MakeLogic_varVec);
      }
      if (array_var* const objArrayVar = any_cast<array_var>(objVariables)) {
        COLLECT(parentAsScope, objArrayVar, Array_vars, MakeArray_varVec);
      }
    }
  } else if (virtual_interface_var* const objVirtualInterfaceVar =
                 any_cast<virtual_interface_var>(this)) {
    if (parentAsScope != nullptr) {
      COLLECT(parentAsScope, objVirtualInterfaceVar, Virtual_interface_vars,
              MakeVirtual_interface_varVec);
    }
  } else if (parameter* const objParameter = any_cast<parameter>(this)) {
    if (parentAsScope != nullptr) {
      COLLECT(parentAsScope, objParameter, Parameters, MakeAnyVec);
    } else if (parentAsDesign != nullptr) {
      COLLECT(parentAsDesign, objParameter, Parameters, MakeAnyVec);
    }
  } else if (param_assign* const objParamAssign =
                 any_cast<param_assign>(this)) {
    if (parentAsScope != nullptr) {
      COLLECT(parentAsScope, objParamAssign, Param_assigns,
              MakeParam_assignVec);
    } else if (parentAsDesign != nullptr) {
      COLLECT(parentAsDesign, objParamAssign, Param_assigns,
              MakeParam_assignVec);
    }
  } else if (scope* const objScope = any_cast<scope>(this)) {
    if (parentAsScope != nullptr) {
      COLLECT(parentAsScope, objScope, Scopes, MakeScopeVec);
    }
  } else if (typespec* const objTypespec = any_cast<typespec>(this)) {
    if (parentAsScope != nullptr) {
      COLLECT(parentAsScope, objTypespec, Typespecs, MakeTypespecVec);
    } else if (parentAsDesign != nullptr) {
      COLLECT(parentAsDesign, objTypespec, Typespecs, MakeTypespecVec);
    }
  } else if (let_decl* const objLetdecl = any_cast<let_decl>(this)) {
    if (parentAsScope != nullptr) {
      COLLECT(parentAsScope, objLetdecl, Let_decls, MakeLet_declVec);
    } else if (parentAsDesign != nullptr) {
      COLLECT(parentAsDesign, objLetdecl, Let_decls, MakeLet_declVec);
    }
  } else if (task_func* const objTaskFunc = any_cast<task_func>(this)) {
    if (parentAsDesign != nullptr) {
      COLLECT(parentAsDesign, objTaskFunc, Task_funcs, MakeTask_funcVec);
    }
  } else if (io_decl* const objIoDecl = any_cast<io_decl>(this)) {
    if (parentAsUdpDefn != nullptr) {
      COLLECT(parentAsUdpDefn, objIoDecl, Io_decls, MakeIo_declVec);
    }
  } else if (table_entry* const objTableEntry = any_cast<table_entry>(this)) {
    if (parentAsUdpDefn != nullptr) {
      COLLECT(parentAsUdpDefn, objTableEntry, Table_entrys, MakeTable_entryVec);
    }
  } else {
    goodParent = parent;
  }

#undef COLLECT
  return VpiParent(goodParent);
}
}  // namespace UHDM
