/*
 Do not modify, auto-generated by script

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   Serializer_restore.cpp
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */
#include <uhdm/Serializer.h>

#include <fcntl.h>
#include <limits.h>
#include <sys/stat.h>
#include <sys/types.h>

#if defined(_MSC_VER)
  #include <io.h>
#else
  #include <unistd.h>
#endif

#include <iostream>
#include <vector>

#include <capnp/message.h>
#include <capnp/serialize-packed.h>

#include "UHDM.capnp.h"
#include <uhdm/uhdm.h>

#include "uhdm/config.h"

namespace uhdm {
static constexpr std::string_view kUnknownRawSymbol = "<unknown>";

template<typename T>
T* Serializer::getObject(uint32_t type, uint32_t index) const {
  if (index == kBadIndex) {
    return nullptr;
  }

  factories_t::const_iterator it = m_factories.find(static_cast<UhdmType>(type));
  return it != m_factories.cend() ? any_cast<T>(it->second->m_objects[index]) : nullptr;
}

struct Serializer::RestoreAdapter {
  void operator()(::Any::Reader reader, Serializer *const serializer, BaseClass *const obj) const {
    // Do NOT call VpiParent function call here! It ends up duplicating the entries in the collections
    // because of calls to OnChildAdded & OnChildRemoved.
    // obj->VpiParent(serializer->getObject(reader.getVpiParent().getType(), reader.getVpiParent().getIndex() - 1));
    obj->m_parent = serializer->getObject<BaseClass>(reader.getParent().getType(), reader.getParent().getIndex() - 1);
    obj->setFile(serializer->m_symbolFactory.getSymbol(SymbolId(reader.getFile(), kUnknownRawSymbol)));
    obj->m_startLine = reader.getStartLine();
    obj->m_startColumn = reader.getStartColumn();
    obj->m_endLine = reader.getEndLine();
    obj->m_endColumn = reader.getEndColumn();
    obj->m_uhdmId = reader.getUhdmId();
  }

<CAPNP_RESTORE_ADAPTERS>
  template<typename T, typename U, typename = typename std::enable_if<std::is_base_of<BaseClass, T>::value>::type>
  void operator()(typename ::capnp::List<U>::Reader reader, Serializer *serializer) const {
    Factory::objects_t& objects = serializer->m_factories[T::kUhdmType]->m_objects;
    uint32_t index = 0;
    for (typename U::Reader subReader : reader)
      operator()(subReader, serializer, any_cast<T>(objects[index++]));
  }
};

const std::vector<vpiHandle> Serializer::restore(const std::filesystem::path& filepath) {
    return restore( filepath.string());
}
const std::vector<vpiHandle> Serializer::restore(const std::string& filepath) {
  purge();
  std::vector<vpiHandle> designs;
  const std::string file = filepath;
  int32_t fileid = open(file.c_str(), O_RDONLY | O_BINARY);
  ::capnp::ReaderOptions options;
  options.traversalLimitInWords = ULLONG_MAX;
  options.nestingLimit = 1024;
  ::capnp::PackedFdMessageReader message(fileid, options);
  UhdmRoot::Reader cap_root = message.getRoot<UhdmRoot>();
  m_version = cap_root.getVersion();
  if (m_version != kVersion) return designs;

  const ::capnp::List<::capnp::Text>::Reader& symbols = cap_root.getSymbols();
  for (const auto& symbol : symbols) {
    m_symbolFactory.registerSymbol(symbol.cStr());
  }

<CAPNP_INIT_FACTORIES>
  // This assignment should happen only after the necessary objects are created.
  m_objId = cap_root.getObjectId();

  RestoreAdapter adapter;
<CAPNP_RESTORE_FACTORIES>

  Factory* const designFactory = m_factories[UhdmType::Design];
  for (auto d : designFactory->m_objects) {
    vpiHandle designH = m_uhdmHandleFactory.make(UhdmType::Design, d);
    designs.emplace_back(designH);
  }

  close(fileid);
  return designs;
}
}  // namespace uhdm
