import argparse
import os
import sys

try:
    import yaml
    HAS_YAML = True
except ImportError:
    HAS_YAML = False

def to_cpp_class_name(name):
    """Converts snake_case name to PascalCase for C++ class."""
    if not name:
        return ""
    # Special handling or just capitalization?
    # User example: 'Design' from 'design'.
    # Standard snake to pascal: 'class_defn' -> 'ClassDefn'?
    # Or just capitalize first letter?
    # The user manual "UHDM/model/design.yaml" says "obj_def: design".
    # Searching for class naming in C++...
    # Assuming PascalCase.
    parts = name.split('_')
    return "".join(p.capitalize() for p in parts)

def parse_yaml_manual(path):
    """Minimal manual parser if PyYAML is missing."""
    data = {}
    with open(path, 'r') as f:
        for line in f:
            line = line.strip()
            if line.startswith("- obj_def:"):
                data['obj_def'] = line.split(":", 1)[1].strip()
            elif line.startswith("- extensions:"): # Note: standard calls it 'extends' in class_defn.yaml, but let's check.
                # In class_defn.yaml line 18: "- extends: scope"
                 pass
            elif line.startswith("- extends:"):
                data['extends'] = line.split(":", 1)[1].strip()
            # We only need obj_def and extends for this PoC
    return data

def parse_yaml(path):
    if HAS_YAML:
        with open(path, 'r') as f:
            content = yaml.safe_load(f)
            data = {}
            if isinstance(content, list):
                for item in content:
                    if isinstance(item, dict):
                        data.update(item)
            elif isinstance(content, dict):
                data = content
            return data
    else:
        return parse_yaml_manual(path)

def generate_header(out_file):
    out_file.write("// AUTOGENERATED POC - DO NOT EDIT\n")
    out_file.write("#include <pybind11/pybind11.h>\n")
    out_file.write("#include <memory>\n") # For std::unique_ptr
    out_file.write("namespace py = pybind11;\n\n")

def generate_binding(data, yaml_path, out_file):
    obj_def = data.get('obj_def')
    if not obj_def:
        print(f"Error: Could not determine class name from {yaml_path}")
        sys.exit(1)

    class_name = to_cpp_class_name(obj_def)
    base_class_name = data.get('extends')
    
    # Best effort header include
    # Assuming header is in uhdm/ directory and matches the yaml filename
    filename = os.path.basename(yaml_path)
    header_name = os.path.splitext(filename)[0] + ".h"
    out_file.write(f"#include <uhdm/{header_name}>\n\n")

    out_file.write(f"void bind_{class_name}(py::module_& m) {{\n")
    
    cpp_class = f"uhdm::{class_name}"
    
    if base_class_name:
        cpp_base_class = f"uhdm::{to_cpp_class_name(base_class_name)}"
        out_file.write(f"  py::class_<{cpp_class}, {cpp_base_class}, std::unique_ptr<{cpp_class}, py::nodelete>>(m, \"{class_name}\");\n")
    else:
        out_file.write(f"  py::class_<{cpp_class}, std::unique_ptr<{cpp_class}, py::nodelete>>(m, \"{class_name}\");\n")
    
    out_file.write("}\n")

def main():
    """
    Usage:
      python3 scripts/pybind_gen_poc.py --yaml model/design.yaml --out output_design.cpp
    """
    parser = argparse.ArgumentParser(description="Generate Pybind11 bindings from UHDM YAML.")
    parser.add_argument("--yaml", required=True, help="Path to one model/*.yaml file")
    parser.add_argument("--out", required=True, help="Output .cpp file path")
    args = parser.parse_args()

    data = parse_yaml(args.yaml)
    
    with open(args.out, 'w') as f:
        generate_header(f)
        generate_binding(data, args.yaml, f)

if __name__ == "__main__":
    main()
