import argparse
import os
import sys

# Use local scripts module for loading
import loader
import config

def generate_header(out_file):
    out_file.write("// AUTOGENERATED POC - DO NOT EDIT\n")
    out_file.write("#include <pybind11/pybind11.h>\n")
    out_file.write("#include <pybind11/stl.h>\n") # For std::vector
    out_file.write("#include <memory>\n") # For std::unique_ptr
    out_file.write("namespace py = pybind11;\n\n")

def generate_binding(model_name, model_def, out_file):
    class_name = config.make_class_name(model_name)
    
    # Best effort header include: use the snake_case model name directly
    # Example: model "design" -> #include <uhdm/design.h>
    header_name = f"{model_name}.h"
    out_file.write(f"#include <uhdm/{header_name}>\n")

    # Include headers for referenced types to avoid incomplete type errors in vectors
    includes = set()
    iter_items = model_def.allitems() if hasattr(model_def, 'allitems') else model_def.items()
    for key, value in iter_items:
        if key in ['class_ref', 'obj_ref']:
             type_name = value.get('type')
             if type_name and type_name != 'any':
                 includes.add(f"#include <uhdm/{type_name}.h>")
    
    for inc in sorted(includes):
        out_file.write(f"{inc}\n")

    out_file.write("\n")
    out_file.write(f"void bind_{class_name}(py::module_& m) {{\n")
    
    cpp_class = f"uhdm::{class_name}"
    
    extends = model_def.get('extends')
    cpp_parent = ""
    if extends:
        cpp_parent = f"uhdm::{config.make_class_name(extends)}"
    elif class_name != "BaseClass":
        # Default inheritance from BaseClass for all classes except BaseClass itself
        cpp_parent = "uhdm::BaseClass"

    py_class_name = class_name # The python-facing class name

    if cpp_parent:
        out_file.write(f"  py::class_<{cpp_class}, {cpp_parent}, std::unique_ptr<{cpp_class}, py::nodelete>> cls(m, \"{py_class_name}\");\n")
    else:
        out_file.write(f"  py::class_<{cpp_class}, std::unique_ptr<{cpp_class}, py::nodelete>> cls(m, \"{py_class_name}\");\n")
    
    # Generate getters
    # Handle robust iteration
    iter_items = model_def.allitems() if hasattr(model_def, 'allitems') else model_def.items()

    for key, value in iter_items:
        if key == 'property':
            # value is dict-like: {'name': ..., 'type': ..., 'card': ..., ...}
            prop_name = value.get('name')
            prop_type = value.get('type')
            card = value.get('card')
            
            # Filter for scalar types
            if prop_type in ['string', 'int', 'bool', 'unsigned int']:
                # The PoC required "get" + PascalCase
                suffix = config.make_func_name(prop_name, card)
                func_name = f"get{suffix}"
                
                # Python attribute name:
                # If 'vpi' key is present, use it (camelCase usually).
                # Otherwise fallback to 'name' (snake_case).
                python_name = value.get('vpi', prop_name)
                
                out_file.write(f"  cls.def_property_readonly(\"{python_name}\", &{cpp_class}::{func_name});\n")

        elif key in ['class_ref', 'obj_ref']:
            prop_name = value.get('name')
            prop_type = value.get('type')
            card = value.get('card')

            # Determine Accessor
            suffix = config.make_func_name(prop_name, card)
            func_name = f"get{suffix}" # e.g. getTopModules
            python_name = prop_name
            
            if card == '1':
                # Return Policy
                # For pointers, reference is usually safe as we don't transfer ownership
                policy = "py::return_value_policy::reference"
                # Use lambda to resolve overload ambiguity (const vs non-const)
                out_file.write(f"  cls.def_property_readonly(\"{python_name}\", []({cpp_class}* self) {{ return self->{func_name}(); }}, {policy});\n")
            
            elif card == 'any':
                # For vectors, we need a lambda to handle nullptr -> empty list
                # And we return by value (copying the vector of pointers), 
                # relying on pybind11 to convert std::vector<T*> to [T*] with reference policy for elements.
                
                # Element type class name
                elem_type = config.make_class_name(value.get('type'))
                elem_cpp_type = f"uhdm::{elem_type}"
                
                out_file.write(f"  cls.def_property_readonly(\"{python_name}\", []({cpp_class}* self) {{\n")
                out_file.write(f"    std::vector<{elem_cpp_type}*> res;\n")
                out_file.write(f"    if (auto* vec = self->{func_name}()) {{\n")
                out_file.write(f"      res.reserve(vec->size());\n")
                out_file.write(f"      res.insert(res.end(), vec->begin(), vec->end());\n")
                out_file.write(f"    }}\n")
                out_file.write(f"    return res;\n")
                out_file.write(f"  }}, py::return_value_policy::reference);\n")

    out_file.write("}\n")

def main():
    parser = argparse.ArgumentParser(description="Generate Pybind11 bindings for all UHDM models.")
    parser.add_argument("--out_dir", default="python/pybind11/bindings/autogen", help="Output directory for generated bindings")
    parser.add_argument("--print-files", action="store_true", help="Print list of files to be generated and exit")
    args = parser.parse_args()

    # Suppress output if we are just printing files for CMake
    if not args.print_files:
        print("Loading models...")
    models = loader.load_models()
    

    if args.print_files:
        # Just print filenames relative to out_dir (or just filenames)
        # CMake expects a list. We'll output absolute paths or paths compatible with how we construct them in CMake.
        # Actually just filenames is best, CMake can prepend dir.
        files = []
        for model_name, model_def in models.items():
            if model_def.get('type') in ['obj_def', 'class_def']:
                class_name = config.make_class_name(model_name)
                files.append(f"bind_{class_name}.cpp")
        
        # Also include the aggregator file
        files.append("bind_all_autogen.cpp")
        
        print(";".join(sorted(files)))
        return

    if not os.path.exists(args.out_dir):
        os.makedirs(args.out_dir)
        
    print(f"Generating bindings for {len(models)} models into {args.out_dir}...")
    
    generated_bind_funcs = []

    for model_name, model_def in models.items():
        # Valid type filter: only obj_def and class_def
        def_type = model_def.get('type')
        if def_type not in ['obj_def', 'class_def']:
            continue
            
        class_name = config.make_class_name(model_name)
        out_filename = f"bind_{class_name}.cpp"
        out_path = os.path.join(args.out_dir, out_filename)
        
        # Store for aggregator
        generated_bind_funcs.append(f"bind_{class_name}")

        with open(out_path, 'w') as f:
            generate_header(f)
            generate_binding(model_name, model_def, f)

    # Generate aggregator: bind_all_autogen.cpp
    aggregator_path = os.path.join(args.out_dir, "bind_all_autogen.cpp")
    
    # Topological sort for correct binding order
    # Graph: class_name -> set(dep_class_names)
    # Actually we just need: class -> extends (0 or 1)
    
    # Map class_name -> model_def
    class_map = {}
    for model_name, model_def in models.items():
        if model_def.get('type') in ['obj_def', 'class_def']:
             name = config.make_class_name(model_name)
             class_map[name] = model_def

    visited = set()
    sorted_classes = []
    
    def visit(name):
        if name in visited:
            return
        visited.add(name)
        
        # Find dependencies (base class)
        # We need to find the model definition for 'name'
        # The 'models' keys are snake_case, 'name' is PascalCase.
        # We used class_map above.
        
        if name not in class_map:
             # External dependency or not in our generaed set (e.g. Serializer if not generated)
             # If it's not generated, we assume it's already bound manually hopefully.
             return
             
        model_def = class_map[name]
        extends = model_def.get('extends')
        if extends:
            base_class = config.make_class_name(extends)
            visit(base_class)
            
        sorted_classes.append(name)

    # Visit all generated classes
    for model_name, model_def in models.items():
        if model_def.get('type') in ['obj_def', 'class_def']:
            class_name = config.make_class_name(model_name)
            visit(class_name)

    with open(aggregator_path, 'w') as f:
        f.write("// AUTOGENERATED POC - DO NOT EDIT\n")
        f.write("#include <pybind11/pybind11.h>\n")
        f.write("\n")
        f.write("namespace py = pybind11;\n\n")
        
        # Forward declarations
        f.write("// Forward declarations\n")
        for func in sorted(generated_bind_funcs):
            f.write(f"void {func}(py::module_& m);\n")
            
        f.write("\n")
        f.write("void bind_all_autogen(py::module_& m) {\n")
        
        # Call in topological order
        # We need to map sorted class names back to bind functions, or just reconstruct strings
        for cls in sorted_classes:
            func_name = f"bind_{cls}"
            # Verify we actually generated this function (should be yes if in class_map)
            # Just to be safe, check if it is in generated_bind_funcs list
            if func_name in generated_bind_funcs:
                f.write(f"  {func_name}(m);\n")
                
        f.write("}\n")
            
    print("Done.")

if __name__ == "__main__":
    main()
