import argparse
import os
import sys

try:
    import yaml
    HAS_YAML = True
except ImportError:
    HAS_YAML = False

def to_cpp_class_name(name):
    """Converts snake_case name to PascalCase for C++ class."""
    if not name:
        return ""
    parts = name.split('_')
    return "".join(p.capitalize() for p in parts)

def parse_yaml_manual(path):
    """Minimal manual parser if PyYAML is missing."""
    items = []
    current_item = {}
    with open(path, 'r') as f:
        for line in f:
            line = line.strip()
            if line.startswith("-"):
                if current_item:
                    items.append(current_item)
                current_item = {}
                line = line[1:].strip() # remove leading dash
            
            if ":" in line:
                key, value = line.split(":", 1)
                current_item[key.strip()] = value.strip()
                
        if current_item:
            items.append(current_item)
    return items

def parse_yaml(path):
    if HAS_YAML:
        with open(path, 'r') as f:
            content = yaml.safe_load(f)
            if isinstance(content, list):
                return content
            elif isinstance(content, dict):
                return [content]
            return []
    else:
        return parse_yaml_manual(path)

def generate_header(out_file):
    out_file.write("// AUTOGENERATED POC - DO NOT EDIT\n")
    out_file.write("#include <pybind11/pybind11.h>\n")
    out_file.write("#include <memory>\n") # For std::unique_ptr
    out_file.write("namespace py = pybind11;\n\n")

def generate_binding(data, yaml_path, out_file):
    # Find obj_def and extends
    obj_def = None
    extends = None
    
    for item in data:
        if 'obj_def' in item:
            obj_def = item['obj_def']
        if 'extends' in item:
            extends = item['extends']
            
    if not obj_def:
        print(f"Error: Could not determine class name from {yaml_path}")
        sys.exit(1)

    class_name = to_cpp_class_name(obj_def)
    
    # Best effort header include
    filename = os.path.basename(yaml_path)
    header_name = os.path.splitext(filename)[0] + ".h"
    out_file.write(f"#include <uhdm/{header_name}>\n\n")

    out_file.write(f"void bind_{class_name}(py::module_& m) {{\n")
    
    cpp_class = f"uhdm::{class_name}"
    
    if extends:
        cpp_base = f"uhdm::{to_cpp_class_name(extends)}"
        out_file.write(f"  py::class_<{cpp_class}, {cpp_base}, std::unique_ptr<{cpp_class}, py::nodelete>> cls(m, \"{class_name}\");\n")
    else:
        out_file.write(f"  py::class_<{cpp_class}, std::unique_ptr<{cpp_class}, py::nodelete>> cls(m, \"{class_name}\");\n")
    
    # Generate getters
    for item in data:
        if 'property' in item:
            prop_name = item['property']
            prop_type = item.get('type')
            
            # Filter for scalar types
            if prop_type in ['string', 'int', 'bool', 'unsigned int']:
                getter_name = "get" + to_cpp_class_name(prop_name)
                # Use pythonic read-only property: obj.prop_name
                out_file.write(f"  cls.def_property_readonly(\"{prop_name}\", &{cpp_class}::{getter_name});\n")

    out_file.write("}\n")

def generate_from_parsed_model(parsed_items, yaml_path, out_path):
    with open(out_path, 'w') as f:
        generate_header(f)
        generate_binding(parsed_items, yaml_path, f)

def main():
    """
    Usage:
      python3 scripts/pybind_gen_poc.py --yaml model/design.yaml --out output_design.cpp
    """
    parser = argparse.ArgumentParser(description="Generate Pybind11 bindings from UHDM YAML.")
    parser.add_argument("--yaml", required=True, help="Path to one model/*.yaml file")
    parser.add_argument("--out", required=True, help="Output .cpp file path")
    args = parser.parse_args()

    data = parse_yaml(args.yaml)
    generate_from_parsed_model(data, args.yaml, args.out)

if __name__ == "__main__":
    main()
