/*
 Do not modify, auto-generated by cloner.py

 Copyright 2019-2020 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   Reducer.cpp
 * Author: hs
 *
 * Created on November 07, 2024, 00:00 AM
 */

#include <uhdm/ExprEval.h>
#include <uhdm/Reducer.h>
#include <uhdm/UhdmFinder.h>
#include <uhdm/Utils.h>
#include <uhdm/uhdm.h>

namespace StringUtils {
// Tokenize "str" at "multichar_separator"; store in "result" array.
std::vector<std::string_view> &tokenizeMulti(std::string_view str, std::string_view multichar_separator,
                                             std::vector<std::string_view> &result) {
  if (str.empty()) return result;

  size_t start = 0;
  size_t end = 0;
  const size_t sepSize = multichar_separator.size();
  const size_t stringSize = str.size();
  for (size_t i = 0; i < stringSize; i++) {
    bool isSeparator = true;
    for (size_t j = 0; j < sepSize; j++) {
      if (i + j >= stringSize) break;
      if (str[i + j] != multichar_separator[j]) {
        isSeparator = false;
        break;
      }
    }
    if (isSeparator) {
      result.emplace_back(str.data() + start, end - start);
      start = end = end + sepSize;
      i = i + sepSize - 1;
    } else {
      ++end;
    }
  }
  result.emplace_back(str.data() + start, end - start);
  return result;
}
}  // namespace StringUtils

namespace uhdm {
template <typename T>
inline const T *getNamedObject(const Factory::objects_t &objects, std::string_view name) {
  if (name.empty()) return nullptr;
  Factory::objects_t::const_iterator it =
      std::find_if(objects.cbegin(), objects.cend(), [&name](const Any *object) { return object->getName() == name; });
  return (it == objects.cend()) ? nullptr : any_cast<T>(*it);
}

void Reducer::addAttempt(const Any *what, Any *with, bool result) {
  ReduceRow &row = m_rows.emplace_back();

  row.m_inputType = UhdmName(what->getUhdmType());
  row.m_inputId = what->getUhdmId();
  row.m_sl = what->getStartLine();
  row.m_sc = what->getStartColumn();
  row.m_el = what->getEndLine();
  row.m_ec = what->getEndColumn();

  if ((with != nullptr) && result) {
    m_swaps.emplace(what, with);

    row.m_outputId = with->getUhdmId();
    row.m_outputType = UhdmName(with->getUhdmType());
    row.m_status = ReduceStatus::REDUCED;
  } else if (!result) {
    row.m_outputId = what->getUhdmId();
    row.m_outputType = row.m_inputType;
    row.m_status = ReduceStatus::INVALID;
  } else {
    row.m_outputId = what->getUhdmId();
    row.m_outputType = row.m_inputType;
    row.m_status = ReduceStatus::NO_CHANGE;
  }

  switch (what->getUhdmType()) {
    case UhdmType::Operation: {
      const Operation *const op = static_cast<const Operation *>(what);
      StrAppend(&row.m_inputType, ":", getOperationName(op->getOpType()));
    } break;

    case UhdmType::FuncCall: {
      const FuncCall *const fc = static_cast<const FuncCall *>(what);
      if (!fc->getName().empty()) StrAppend(&row.m_inputType, ":", fc->getName());
    } break;

    case UhdmType::SysFuncCall: {
      const SysFuncCall *const sfc = static_cast<const SysFuncCall *>(what);
      if (!sfc->getName().empty()) StrAppend(&row.m_inputType, ":", sfc->getName());
    } break;

    case UhdmType::Variable: {
      const Variable *const v = static_cast<const Variable *>(what);
      if (!v->getName().empty()) StrAppend(&row.m_inputType, ":", v->getName());
    } break;

    case UhdmType::IODecl: {
      const IODecl *const iod = static_cast<const IODecl *>(what);
      if (!iod->getName().empty()) StrAppend(&row.m_inputType, ":", iod->getName());
    } break;

    case UhdmType::EnumConst: {
      const EnumConst *const ec = static_cast<const EnumConst *>(what);
      if (!ec->getName().empty()) StrAppend(&row.m_inputType, ":", ec->getName());
    } break;

    case UhdmType::Net: {
      const Net *const n = static_cast<const Net *>(what);
      if (!n->getName().empty()) StrAppend(&row.m_inputType, ":", n->getName());
    }

    default: break;
  }
}

void Reducer::reduce(const ArrayExpr *object) {
  Expr *rexpr = nullptr;
  ExprEval eval(this, false);
  bool result = eval.reduceExpr(object, object->getParent(), &rexpr, false);
  addAttempt(object, rexpr, result);
}

void Reducer::reduce(const Operation *object) {
  Expr *rexpr = nullptr;
  ExprEval eval(this, false);
  bool result = eval.reduceExpr(object, object->getParent(), &rexpr, false);
  addAttempt(object, rexpr, result);
}

void Reducer::reduce(const RefObj *object) {
  Expr *rexpr = nullptr;
  ExprEval eval(this, false);
  bool result = eval.reduceExpr(object, object->getParent(), &rexpr, false);
  addAttempt(object, rexpr, result);
}

void Reducer::reduce(const SysFuncCall *object) {
  Expr *rexpr = nullptr;
  ExprEval eval(this, false);
  bool result = eval.reduceExpr(object, object->getParent(), &rexpr, false);
  addAttempt(object, rexpr, result);
}

const TaskFunc *Reducer::getTaskFunc(std::string_view name, const Any *inst, const Any *pexpr,
                                     bool muteErrors /* = false */) {
  return nullptr;
}

const Any *Reducer::getObject(std::string_view name, const Any *inst, const Any *pexpr, bool muteErrors /* = false */) {
  return m_finder.findObject(name, pexpr);
}

void Reducer::setRange(const Constant *c, uint16_t lr, uint16_t rr) {
  if (c == nullptr) return;
  if ((lr == 0) && (rr == 0)) return;

  RefTypespec *const rt = m_serializer->make<RefTypespec>();
  rt->setParent(const_cast<Constant *>(c));

  LogicTypespec *const lt = m_serializer->make<LogicTypespec>();
  rt->setActual(lt);
  const_cast<Constant *>(c)->setTypespec(rt);

  Range *const r = m_serializer->make<Range>();
  r->setParent(lt);

  RangeCollection *const ranges = lt->getRanges(true);
  ranges->emplace_back(r);

  Constant *const lc = m_serializer->make<Constant>();
  lc->setValue(std::to_string(lr));
  r->setLeftExpr(lc);

  Constant *const rc = m_serializer->make<Constant>();
  rc->setValue(std::to_string(rr));
  r->setRightExpr(rc);
}

bool Reducer::loopDetected() {
  // @todo: Need to implement loop detection in different way. Currently
  // returning false.
  return false;
}

const Design *Reducer::getDesign(std::string_view name) const {
  Factory *const factory = m_serializer->getFactory<Design>();
  const Factory::objects_t &designs = factory->getObjects();
  if (name.empty() && (designs.size() == 1)) {
    return any_cast<Design>(designs.back());
  }
  return getNamedObject<Design>(designs, name);
}

const Package *Reducer::getPackage(std::string_view name) const {
  Factory *const factory = m_serializer->getFactory<Package>();
  const Factory::objects_t &packages = factory->getObjects();
  return getNamedObject<Package>(packages, name);
}

// getComplexValue(
// map<Scope*, name, expr*>
// iterate thriough scope and it know all the trees and get aal the expression
// then if it is complex then fill the ,map and utilize the lookup form built
// map

Expr *Reducer::getComplexValue(const Any *any, std::string_view name) const {
  const Any *p = any;
  while (p != nullptr) {
    if (const Scope *const s = any_cast<Scope>(p)) {
      if (const ParamAssignCollection *param_assigns = s->getParamAssigns()) {
        for (ParamAssign *param : *param_assigns) {
          if (param && param->getLhs()) {
            if (param->getLhs()->getName() == name) {
              if (Expr *exp = param->getRhs<Expr>()) {
                return exp;
              }
            }
          }
        }
      }
    }
    p = p->getParent();
  }
  return nullptr;
}

// on the fly just get the expr using name
Any *Reducer::getValue(std::string_view name, const Any *inst, const Any *pexpr, bool muteErrors /* = false */) {
  // Value *sval = nullptr;
  Any *result = nullptr;
  if (loopDetected()) {
    return nullptr;
  }
  if (m_checkForLoops) {
    m_stackLevel++;
  }
  if (name.find("::") != std::string::npos) {
    std::vector<std::string_view> res;
    StringUtils::tokenizeMulti(name, "::", res);
    if (res.size() > 1) {
      const std::string_view packName = res[0];
      const std::string_view varName = res[1];
      if (const Package *pack = getPackage(packName)) {
        if (Expr *val = getComplexValue(pack, varName)) {
          result = val;
          /*
          if (result->getUhdmType() == UhdmType::Operation) {
            Operation *op = (Operation *)result;
            const Typespec *opts = nullptr;
            if (RefTypespec *rt = op->getTypespec()) {
              opts = rt->getActual();
            }
            ExprEval eval;
            if (expr *res = eval.flattenPatternAssignments(
                    s, opts, (expr *)result)) {
              if (res->getUhdmType() == uhdmoperation) {
                op->Operands(((operation *)res)->Operands());
              }
            }
          }
          */
        }
        if (result == nullptr) {
          // Need to get input about Value
          // if (Value *sval = pack->getValue(varName)) {
          //  constant *c = s.MakeConstant();
          //  c->VpiValue(sval->uhdmValue());
          //  setRange(c, sval, compileDesign);
          //  c->VpiDecompile(sval->decompiledValue());
          //  c->VpiConstType(sval->vpiValType());
          //  c->VpiSize(sval->getSize());
          //  result = c;
          //}
        }
      }
    }
  }

  if (result == nullptr) {
    if (Expr *val = getComplexValue(pexpr, name)) {
      result = val;
      if (result->getUhdmType() == UhdmType::Constant) {
        // sval = instance->getValue(name);
        // if (sval && sval->isValid()) {
        //   setRange((constant *)result, sval);
        // }
      }
    }
    if (result == nullptr) {
      // sval = instance->getValue(name);
      // if (sval && sval->isValid()) {
      //   constant *c = s.MakeConstant();
      //   c->VpiValue(sval->uhdmValue());
      //   setRange(c, sval, compileDesign);
      //   c->VpiDecompile(sval->decompiledValue());
      //   c->VpiConstType(sval->vpiValType());
      //   c->VpiSize(sval->getSize());
      //   result = c;
      // }
    }
  }

  if (result) {
    UhdmType resultType = result->getUhdmType();
    if (resultType == UhdmType::Constant) {
    } else if (resultType == UhdmType::RefObj) {
      if (result->getName() != name) {
        if (Any *tmp = getValue(result->getName(), nullptr, pexpr)) {
          result = tmp;
        }
      }
    } else if ((resultType == UhdmType::Operation) || (resultType == UhdmType::HierPath) ||
               (resultType == UhdmType::BitSelect) || (resultType == UhdmType::SysFuncCall)) {
      Expr *rexpr = nullptr;
      ExprEval eval(this, muteErrors);
      if (eval.reduceExpr(any_cast<Expr>(result), pexpr, &rexpr, muteErrors)) {
        result = rexpr;
      }
    }
  }
  if (m_checkForLoops) {
    m_stackLevel--;
  }
  return result;
}

static constexpr std::string_view statusToStr(ReduceStatus s) {
  switch (s) {
    case ReduceStatus::REDUCED: return "REDUCED";
    case ReduceStatus::INVALID: return "INVALID";
    case ReduceStatus::NO_CHANGE: return "NO_CHANGE";
  }
  return "";
}

void Reducer::printAttempts(std::ostream &os) const {
  constexpr std::string_view kInputTypeH = "InputType";
  constexpr std::string_view kInputIdH = "InputId";
  constexpr std::string_view kSLH = "SL";
  constexpr std::string_view kSCH = "SC";
  constexpr std::string_view kELH = "EL";
  constexpr std::string_view kECH = "EC";
  constexpr std::string_view kOutputTypeH = "OutputType";
  constexpr std::string_view kOutputIdH = "OutputId";
  constexpr std::string_view kStatusH = "Status";

  size_t wInputType = kInputTypeH.length();
  size_t wInputId = kInputIdH.length();
  size_t wSL = kSLH.length();
  size_t wSC = kSCH.length();
  size_t wEL = kELH.length();
  size_t wEC = kECH.length();
  size_t wOutputType = kOutputTypeH.length();
  size_t wOutputId = kOutputIdH.length();
  size_t wStatus =
      std::max({kStatusH.length(), statusToStr(ReduceStatus::REDUCED).length(),
                statusToStr(ReduceStatus::INVALID).length(), statusToStr(ReduceStatus::NO_CHANGE).length()});

  // --- compute max width per column ---
  for (const ReduceRow &r : m_rows) {
    wInputType = std::max(wInputType, r.m_inputType.length());
    wInputId = std::max(wInputId, std::to_string(r.m_inputId).length());
    wSL = std::max(wSL, std::to_string(r.m_sl).length());
    wSC = std::max(wSC, std::to_string(r.m_sc).length());
    wEL = std::max(wEL, std::to_string(r.m_el).length());
    wEC = std::max(wEC, std::to_string(r.m_ec).length());
    wOutputType = std::max(wOutputType, r.m_outputType.length());
    wOutputId = std::max(wOutputId, std::to_string(r.m_outputId).length());
  }

  constexpr size_t kPad = 2;
  wInputId += kPad;
  wSL += kPad;
  wSC += kPad;
  wEL += kPad;
  wEC += kPad;
  wOutputId += kPad;
  wStatus += kPad;

  wSL = wSC = wEL = wEC = std::max({wSL, wSC, wEL, wEC});
  size_t wTable = wInputType + wInputId + wSL + wSC + wEL + wEC + wOutputType + wOutputId + wStatus + 1;

  auto printBanner = [&](std::string_view txt) {
    size_t pad = wTable > txt.size() ? wTable - txt.size() : 0;
    os << std::string(pad / 2, '=') << txt << std::string(pad - (pad / 2), '=') << '\n';
  };

  printBanner(" REDUCTION START ");

  // --- optional header ---
  os << std::setw(wInputType) << std::left << kInputTypeH << std::setw(wInputId) << std::right << kInputIdH
     << std::setw(wSL) << "SL" << std::setw(wSC) << kSCH << std::setw(wEL) << kELH << std::setw(wEC) << kECH << " "
     << std::setw(wOutputType) << std::left << kOutputTypeH << std::setw(wOutputId) << std::right << kOutputIdH
     << std::setw(wStatus) << kStatusH << '\n';

  os << std::string(wTable, '-') << '\n';

  // --- rows ---
  for (const ReduceRow &r : m_rows) {
    os << std::setw(wInputType) << std::left << r.m_inputType << std::setw(wInputId) << std::right << r.m_inputId
       << std::setw(wSL) << r.m_sl << std::setw(wSC) << r.m_sc << std::setw(wEL) << r.m_el << std::setw(wEC) << r.m_ec
       << " " << std::setw(wOutputType) << std::left << r.m_outputType << std::setw(wOutputId) << std::right
       << r.m_outputId << std::setw(wStatus) << statusToStr(r.m_status) << '\n';
  }

  printBanner(" REDUCTION END ");
}

void Reducer::reduce(bool verbose) {
  if (Factory *const factory = m_serializer->getFactory<Operation>()) {
    const std::vector<Any *> objects(factory->getObjects());
    for (const Any *object : objects) {
      reduce(static_cast<const Operation *>(object));
    }
  }

  if (Factory *const factory = m_serializer->getFactory<SysFuncCall>()) {
    const std::vector<Any *> objects(factory->getObjects());
    for (const Any *object : objects) {
      reduce(static_cast<const SysFuncCall *>(object));
    }
  }

  if (Factory *const factory = m_serializer->getFactory<CaseItem>()) {
    const std::vector<Any *> objects(factory->getObjects());
    for (const Any *object : objects) {
      if (const AnyCollection *const collection = static_cast<const CaseItem *>(object)->getExprs()) {
        for (const Any *expr : *collection) {
          if (const RefObj *const ro = any_cast<RefObj>(expr)) {
            reduce(ro);
          }
        }
      }
    }
  }

  for (auto &[what, with] : m_swaps) {
    if (const Any *p = what->getParent()) {
      with->setParent(const_cast<Any *>(p), true);
      const_cast<Any *>(what)->setParent(nullptr);
    }
  }

  m_serializer->swap(m_swaps);
  if (verbose) printAttempts(std::cout);
}
}  // namespace uhdm
