/*
 Do not modify, auto-generated by cloner.py

 Copyright 2019-2020 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   Reducer.cpp
 * Author: hs
 *
 * Created on November 07, 2024, 00:00 AM
 */

#include <uhdm/ExprEval.h>
#include <uhdm/Reducer.h>
#include <uhdm/UhdmFinder.h>
#include <uhdm/uhdm.h>

namespace StringUtils {
// Tokenize "str" at "multichar_separator"; store in "result" array.
std::vector<std::string_view> &tokenizeMulti(std::string_view str, std::string_view multichar_separator,
                                             std::vector<std::string_view> &result) {
  if (str.empty()) return result;

  size_t start = 0;
  size_t end = 0;
  const size_t sepSize = multichar_separator.size();
  const size_t stringSize = str.size();
  for (size_t i = 0; i < stringSize; i++) {
    bool isSeparator = true;
    for (size_t j = 0; j < sepSize; j++) {
      if (i + j >= stringSize) break;
      if (str[i + j] != multichar_separator[j]) {
        isSeparator = false;
        break;
      }
    }
    if (isSeparator) {
      result.emplace_back(str.data() + start, end - start);
      start = end = end + sepSize;
      i = i + sepSize - 1;
    } else {
      ++end;
    }
  }
  result.emplace_back(str.data() + start, end - start);
  return result;
}
}  // namespace StringUtils

namespace uhdm {
template <typename T>
inline const T *getNamedObject(const Factory::objects_t &objects, std::string_view name) {
  if (name.empty()) return nullptr;
  Factory::objects_t::const_iterator it =
      std::find_if(objects.cbegin(), objects.cend(), [&name](const Any *object) { return object->getName() == name; });
  return (it == objects.cend()) ? nullptr : any_cast<T>(*it);
}

void Reducer::addAttempt(const Any *what, Any *with, bool result) {
  ReduceRow &row = m_rows.emplace_back();

  row.m_inputType = UhdmName(what->getUhdmType());
  row.m_inputId = what->getUhdmId();

  if ((with != nullptr) && result) {
    m_swaps.emplace(what, with);

    row.m_outputId = with->getUhdmId();
    row.m_outputType = UhdmName(with->getUhdmType());
    row.m_status = ReduceStatus::REDUCED;
  } else if (!result) {
    row.m_outputId = what->getUhdmId();
    row.m_outputType = row.m_inputType;
    row.m_status = ReduceStatus::INVALID;
  } else {
    row.m_outputId = what->getUhdmId();
    row.m_outputType = row.m_inputType;
    row.m_status = ReduceStatus::NO_CHANGE;
  }
}

void Reducer::reduce(const ArrayExpr *object) {
  Expr *rexpr = nullptr;
  ExprEval eval(this, false);
  bool result = eval.reduceExpr(object, object->getParent(), &rexpr, false);
  addAttempt(object, rexpr, result);
}

void Reducer::reduce(const Operation *object) {
  Expr *rexpr = nullptr;
  ExprEval eval(this, false);
  bool result = eval.reduceExpr(object, object->getParent(), &rexpr, false);
  addAttempt(object, rexpr, result);
}

void Reducer::reduce(const RefObj *object) {
  Expr *rexpr = nullptr;
  ExprEval eval(this, false);
  bool result = eval.reduceExpr(object, object->getParent(), &rexpr, false);
  addAttempt(object, rexpr, result);
}

void Reducer::reduce(const SysFuncCall *object) {
  Expr *rexpr = nullptr;
  ExprEval eval(this, false);
  bool result = eval.reduceExpr(object, object->getParent(), &rexpr, false);
  addAttempt(object, rexpr, result);
}

const TaskFunc *Reducer::getTaskFunc(std::string_view name, const Any *inst, const Any *pexpr,
                                     bool muteErrors /* = false */) {
  return nullptr;
}

const Any *Reducer::getObject(std::string_view name, const Any *inst, const Any *pexpr, bool muteErrors /* = false */) {
  return m_finder.findObject(name, pexpr);
}

void Reducer::setRange(const Constant *c, uint16_t lr, uint16_t rr) {
  if (c == nullptr) return;
  if ((lr == 0) && (rr == 0)) return;

  RefTypespec *const rt = m_serializer->make<RefTypespec>();
  rt->setParent(const_cast<Constant *>(c));

  LogicTypespec *const lt = m_serializer->make<LogicTypespec>();
  rt->setActual(lt);
  const_cast<Constant *>(c)->setTypespec(rt);

  Range *const r = m_serializer->make<Range>();
  r->setParent(lt);

  RangeCollection *const ranges = lt->getRanges(true);
  ranges->emplace_back(r);

  Constant *const lc = m_serializer->make<Constant>();
  lc->setValue(std::to_string(lr));
  r->setLeftExpr(lc);

  Constant *const rc = m_serializer->make<Constant>();
  rc->setValue(std::to_string(rr));
  r->setRightExpr(rc);
}

bool Reducer::loopDetected() {
  // @todo: Need to implement loop detection in different way. Currently
  // returning false.
  return false;
}

const Design *Reducer::getDesign(std::string_view name) const {
  Factory *const factory = m_serializer->getFactory<Design>();
  const Factory::objects_t &designs = factory->getObjects();
  if (name.empty() && (designs.size() == 1)) {
    return any_cast<Design>(designs.back());
  }
  return getNamedObject<Design>(designs, name);
}

const Package *Reducer::getPackage(std::string_view name) const {
  Factory *const factory = m_serializer->getFactory<Package>();
  const Factory::objects_t &packages = factory->getObjects();
  return getNamedObject<Package>(packages, name);
}

// getComplexValue(
// map<Scope*, name, expr*>
// iterate thriough scope and it know all the trees and get aal the expression
// then if it is complex then fill the ,map and utilize the lookup form built
// map

Expr *Reducer::getComplexValue(const Any *any, std::string_view name) const {
  const Any *p = any;
  while (p != nullptr) {
    if (const Scope *const s = any_cast<Scope>(p)) {
      if (const ParamAssignCollection *param_assigns = s->getParamAssigns()) {
        for (ParamAssign *param : *param_assigns) {
          if (param && param->getLhs()) {
            if (param->getLhs()->getName() == name) {
              if (Expr *exp = param->getRhs<Expr>()) {
                return exp;
              }
            }
          }
        }
      }
    }
    p = p->getParent();
  }
  return nullptr;
}

// on the fly just get the expr using name
Any *Reducer::getValue(std::string_view name, const Any *inst, const Any *pexpr, bool muteErrors /* = false */) {
  // Value *sval = nullptr;
  Any *result = nullptr;
  if (loopDetected()) {
    return nullptr;
  }
  if (m_checkForLoops) {
    m_stackLevel++;
  }
  if (name.find("::") != std::string::npos) {
    std::vector<std::string_view> res;
    StringUtils::tokenizeMulti(name, "::", res);
    if (res.size() > 1) {
      const std::string_view packName = res[0];
      const std::string_view varName = res[1];
      if (const Package *pack = getPackage(packName)) {
        if (Expr *val = getComplexValue(pack, varName)) {
          result = val;
          /*
          if (result->getUhdmType() == UhdmType::Operation) {
            Operation *op = (Operation *)result;
            const Typespec *opts = nullptr;
            if (RefTypespec *rt = op->getTypespec()) {
              opts = rt->getActual();
            }
            ExprEval eval;
            if (expr *res = eval.flattenPatternAssignments(
                    s, opts, (expr *)result)) {
              if (res->getUhdmType() == uhdmoperation) {
                op->Operands(((operation *)res)->Operands());
              }
            }
          }
          */
        }
        if (result == nullptr) {
          // Need to get input about Value
          // if (Value *sval = pack->getValue(varName)) {
          //  constant *c = s.MakeConstant();
          //  c->VpiValue(sval->uhdmValue());
          //  setRange(c, sval, compileDesign);
          //  c->VpiDecompile(sval->decompiledValue());
          //  c->VpiConstType(sval->vpiValType());
          //  c->VpiSize(sval->getSize());
          //  result = c;
          //}
        }
      }
    }
  }

  if (result == nullptr) {
    if (Expr *val = getComplexValue(pexpr, name)) {
      result = val;
      if (result->getUhdmType() == UhdmType::Constant) {
        // sval = instance->getValue(name);
        // if (sval && sval->isValid()) {
        //   setRange((constant *)result, sval);
        // }
      }
    }
    if (result == nullptr) {
      // sval = instance->getValue(name);
      // if (sval && sval->isValid()) {
      //   constant *c = s.MakeConstant();
      //   c->VpiValue(sval->uhdmValue());
      //   setRange(c, sval, compileDesign);
      //   c->VpiDecompile(sval->decompiledValue());
      //   c->VpiConstType(sval->vpiValType());
      //   c->VpiSize(sval->getSize());
      //   result = c;
      // }
    }
  }

  if (result) {
    UhdmType resultType = result->getUhdmType();
    if (resultType == UhdmType::Constant) {
    } else if (resultType == UhdmType::RefObj) {
      if (result->getName() != name) {
        if (Any *tmp = getValue(result->getName(), nullptr, pexpr)) {
          result = tmp;
        }
      }
    } else if ((resultType == UhdmType::Operation) || (resultType == UhdmType::HierPath) ||
               (resultType == UhdmType::BitSelect) || (resultType == UhdmType::SysFuncCall)) {
      Expr *rexpr = nullptr;
      ExprEval eval(this, muteErrors);
      if (eval.reduceExpr(any_cast<Expr>(result), pexpr, &rexpr, muteErrors)) {
        result = rexpr;
      }
    }
  }
  if (m_checkForLoops) {
    m_stackLevel--;
  }
  return result;
}

static std::string_view statusToStr(ReduceStatus s) {
  switch (s) {
    case ReduceStatus::REDUCED: return "REDUCED";
    case ReduceStatus::INVALID: return "INVALID";
    case ReduceStatus::NO_CHANGE: return "NO_CHANGE";
  }
  return "";
}

void Reducer::printAttempts(std::ostream &os) const {
  constexpr uint32_t kInputTypeW = 16;
  constexpr uint32_t kInputIdW = 8;
  constexpr uint32_t kOutputTypeW = 16;
  constexpr uint32_t kOutputIdW = 8;
  constexpr uint32_t kStatusW = 10;
  constexpr uint32_t kTableW = kInputTypeW + kInputIdW + kOutputTypeW + kOutputIdW + kStatusW;

  auto printBanner = [&](std::string_view txt) {
    uint32_t pad = kTableW - txt.size();
    os << std::string(pad / 2, '=') << txt << std::string(pad - (pad / 2), '=') << '\n';
  };

  printBanner(" REDUCTION START ");

  os << std::left << std::setw(kInputTypeW) << "InputObjType" << std::right << std::setw(kInputIdW) << "InputId"
     << std::left << std::setw(kOutputTypeW) << " OutputObjType" << std::right << std::setw(kOutputIdW) << "OutputId"
     << std::right << std::setw(kStatusW) << "Status" << '\n';

  os << std::string(kTableW, '-') << '\n';

  for (const auto &r : m_rows) {
    os << std::left << std::setw(kInputTypeW) << r.m_inputType << std::right << std::setw(kInputIdW) << r.m_inputId
       << std::left << " " << std::setw(kOutputTypeW - 1) << r.m_outputType << std::right << std::setw(kOutputIdW)
       << r.m_outputId << std::right << std::setw(kStatusW) << statusToStr(r.m_status) << '\n';
  }

  printBanner(" REDUCTION END ");
}

void Reducer::reduce(bool verbose) {
  if (Factory *const factory = m_serializer->getFactory<Operation>()) {
    for (const Any *object : factory->getObjects()) {
      reduce(static_cast<const Operation *>(object));
    }
  }

  if (Factory *const factory = m_serializer->getFactory<SysFuncCall>()) {
    for (const Any *object : factory->getObjects()) {
      reduce(static_cast<const SysFuncCall *>(object));
    }
  }

  if (Factory *const factory = m_serializer->getFactory<CaseItem>()) {
    for (const Any *object : factory->getObjects()) {
      if (const AnyCollection *const collection = static_cast<const CaseItem *>(object)->getExprs()) {
        for (const Any *expr : *collection) {
          if (const RefObj *const ro = any_cast<RefObj>(expr)) {
            reduce(ro);
          }
        }
      }
    }
  }

  for (auto &[what, with] : m_swaps) {
    if (const Any *p = what->getParent()) {
      with->setParent(const_cast<Any *>(p), true);
      const_cast<Any *>(what)->setParent(nullptr);
    }
  }

  m_serializer->swap(m_swaps);
  if (verbose) printAttempts(std::cout);
}
}  // namespace uhdm
