name: 'main'

on:
  push:
  pull_request:

jobs:
  linux-gcc:
    name: ubuntu-with-${{ matrix.mode }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        mode:
        - tclgen
        - pygen

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt install -y g++-9 build-essential cmake tclsh

    - name: Git pull
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Use ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: linux-gcc-cache

    - name: Configure shell
      run: |
        echo 'CC=gcc-9' >> $GITHUB_ENV
        echo 'CXX=g++-9' >> $GITHUB_ENV
        echo 'PATH=/usr/lib/ccache:'"$PATH" >> $GITHUB_ENV
        echo 'PREFIX=/tmp/uhdm-install' >> $GITHUB_ENV

        if [[ "${{ matrix.mode }}" = "pygen" ]] ; then
          echo 'WITH_PYTHON_GENERATOR=ON' >> $GITHUB_ENV
        else
          echo 'WITH_PYTHON_GENERATOR=OFF' >> $GITHUB_ENV
        fi

    - name: Show shell configuration
      run: |
        env
        which cmake && cmake --version
        which make && make --version
        which tclsh && echo 'puts [info patchlevel];exit 0' | tclsh
        which $CC && $CC --version
        which $CXX && $CXX --version

    - name: Build & Test
      run: |
        make release
        make test
        make install
        make test_install

  macos:
    name: macos-with-${{ matrix.mode }}
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        mode:
        - tclgen
        - pygen

    steps:
    - name: Install dependencies
      run: |
       brew update
       brew install cmake capnp

    - name: Git pull
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Use ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: macos-cache

    - name: Configure shell
      run: |
        echo "PATH=$(brew --prefix)/opt/ccache/libexec:$PATH" >> $GITHUB_ENV

        if [[ "${{ matrix.mode }}" = "pygen" ]] ; then
          echo 'WITH_PYTHON_GENERATOR=ON' >> $GITHUB_ENV
        else
          echo 'WITH_PYTHON_GENERATOR=OFF' >> $GITHUB_ENV
        fi

    - name: Build & Test
      run: |
        make release
        make test

  msys2-gcc:
    name: msys2-gcc-with-${{ matrix.mode }}
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
      matrix:
        mode:
        - tclgen
        - pygen

    steps:
    - name: Setup Msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: true
        install: make cmake ninja gcc python
      env:
        MSYS2_PATH_TYPE: inherit

    - name: Configure Git
      run: git config --global core.autocrlf input
      shell: bash

    - name: Git pull
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Configure shell
      run: |
        echo 'CC=gcc' >> $GITHUB_ENV
        echo 'CXX=g++' >> $GITHUB_ENV
        echo 'PREFIX=$PWD/install' >> $GITHUB_ENV
        echo 'CMAKE_GENERATOR=Ninja' >> $GITHUB_ENV
        echo 'NO_TCMALLOC=On' >> $GITHUB_ENV
        echo 'TEST_TMPDIR=C:\temp' >> $GITHUB_ENV

        if [[ "${{ matrix.mode }}" = "pygen" ]] ; then
          echo 'WITH_PYTHON_GENERATOR=ON' >> $GITHUB_ENV
        else
          echo 'WITH_PYTHON_GENERATOR=OFF' >> $GITHUB_ENV
        fi

    - name: Show shell configuration
      run: |
        env
        where cmake && cmake --version
        where make && make --version
        where ninja && ninja --version
        where tclsh && echo 'puts [info patchlevel];exit 0' | tclsh
        where $CC && $CC --version
        where $CXX && $CXX --version

    - name: Build & Test
      run: |
        make release
        make test
        make install
        make test_install

  windows-msvc:
    name: windows-with-${{ matrix.mode }}
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
      matrix:
        mode:
        - tclgen
        - pygen

    steps:
    - name: Install Core Dependencies
      run: |
        choco install -y make

    - run: git config --global core.autocrlf input
      shell: bash

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Build & Test
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

        set CC=cl
        set CXX=cl
        set PREFIX=%GITHUB_WORKSPACE%\install
        set CMAKE_GENERATOR=Ninja
        set NO_TCMALLOC=On
        set CPU_CORES=%NUMBER_OF_PROCESSORS%

        set MAKE_DIR=C:\make\bin
        set TCL_DIR=%PROGRAMFILES%\Git\mingw64\bin
        set PATH=%MAKE_DIR%;%TCL_DIR%;%PATH%
        set TEST_TMPDIR=C:\temp

        if "${{ matrix.mode }}" == "pygen" (
          set WITH_PYTHON_GENERATOR=ON
        ) else (
          set WITH_PYTHON_GENERATOR=OFF
        )

        set
        where cmake && cmake --version
        where make && make --version
        where ninja && ninja --version

        make release
        make test
        make install
        make test_install
